// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"time"

	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ClearOmitted0) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint32 /* 19 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "astruct":
			err = z.AStruct.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "AStruct")
				return
			}
			zb0001Mask |= 0x1
		case "bstruct":
			err = z.BStruct.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "BStruct")
				return
			}
			zb0001Mask |= 0x2
		case "astructptr":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AStructPtr")
					return
				}
				z.AStructPtr = nil
			} else {
				if z.AStructPtr == nil {
					z.AStructPtr = new(ClearOmittedA)
				}
				err = z.AStructPtr.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "AStructPtr")
					return
				}
			}
			zb0001Mask |= 0x4
		case "bstructptr":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "BStructPtr")
					return
				}
				z.BStructPtr = nil
			} else {
				if z.BStructPtr == nil {
					z.BStructPtr = new(ClearOmittedA)
				}
				err = z.BStructPtr.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "BStructPtr")
					return
				}
			}
			zb0001Mask |= 0x8
		case "aext":
			err = z.AExt.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "AExt")
				return
			}
			zb0001Mask |= 0x10
		case "aptrnamedstr":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "APtrNamedStr")
					return
				}
				z.APtrNamedStr = nil
			} else {
				if z.APtrNamedStr == nil {
					z.APtrNamedStr = new(NamedStringCO)
				}
				{
					var zb0002 string
					zb0002, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "APtrNamedStr")
						return
					}
					*z.APtrNamedStr = NamedStringCO(zb0002)
				}
			}
			zb0001Mask |= 0x20
		case "anamedstruct":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "ANamedStruct")
				return
			}
			var zb0003Mask uint8 /* 2 bits */
			_ = zb0003Mask
			for zb0003 > 0 {
				zb0003--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "ANamedStruct")
					return
				}
				switch msgp.UnsafeString(field) {
				case "a":
					z.ANamedStruct.A, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "ANamedStruct", "A")
						return
					}
					zb0003Mask |= 0x1
				case "b":
					z.ANamedStruct.B, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "ANamedStruct", "B")
						return
					}
					zb0003Mask |= 0x2
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "ANamedStruct")
						return
					}
				}
			}
			// Clear omitted fields.
			if zb0003Mask != 0x3 {
				if (zb0003Mask & 0x1) == 0 {
					z.ANamedStruct.A = ""
				}
				if (zb0003Mask & 0x2) == 0 {
					z.ANamedStruct.B = ""
				}
			}
			zb0001Mask |= 0x40
		case "aptrnamedstruct":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "APtrNamedStruct")
					return
				}
				z.APtrNamedStruct = nil
			} else {
				if z.APtrNamedStruct == nil {
					z.APtrNamedStruct = new(NamedStructCO)
				}
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "APtrNamedStruct")
					return
				}
				var zb0004Mask uint8 /* 2 bits */
				_ = zb0004Mask
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "APtrNamedStruct")
						return
					}
					switch msgp.UnsafeString(field) {
					case "a":
						z.APtrNamedStruct.A, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "APtrNamedStruct", "A")
							return
						}
						zb0004Mask |= 0x1
					case "b":
						z.APtrNamedStruct.B, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "APtrNamedStruct", "B")
							return
						}
						zb0004Mask |= 0x2
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "APtrNamedStruct")
							return
						}
					}
				}
				// Clear omitted fields.
				if zb0004Mask != 0x3 {
					if (zb0004Mask & 0x1) == 0 {
						z.APtrNamedStruct.A = ""
					}
					if (zb0004Mask & 0x2) == 0 {
						z.APtrNamedStruct.B = ""
					}
				}
			}
			zb0001Mask |= 0x80
		case "someembed2":
			z.SomeEmbed, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SomeEmbed")
				return
			}
			zb0001Mask |= 0x100
		case "embeddablestruct2":
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "EmbeddableStructCO2")
				return
			}
			var zb0005Mask uint8 /* 1 bits */
			_ = zb0005Mask
			for zb0005 > 0 {
				zb0005--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "EmbeddableStructCO2")
					return
				}
				switch msgp.UnsafeString(field) {
				case "someembed2":
					z.EmbeddableStructCO2.SomeEmbed2, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "EmbeddableStructCO2", "SomeEmbed2")
						return
					}
					zb0005Mask |= 0x1
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "EmbeddableStructCO2")
						return
					}
				}
			}
			// Clear omitted fields.
			if (zb0005Mask & 0x1) == 0 {
				z.EmbeddableStructCO2.SomeEmbed2 = ""
			}

			zb0001Mask |= 0x200
		case "atime":
			z.ATime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "ATime")
				return
			}
			zb0001Mask |= 0x400
		case "aslice":
			var zb0006 uint32
			zb0006, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "ASlice")
				return
			}
			if cap(z.ASlice) >= int(zb0006) {
				z.ASlice = (z.ASlice)[:zb0006]
			} else {
				z.ASlice = make([]int, zb0006)
			}
			for za0001 := range z.ASlice {
				z.ASlice[za0001], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "ASlice", za0001)
					return
				}
			}
			zb0001Mask |= 0x800
		case "amap":
			var zb0007 uint32
			zb0007, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "AMap")
				return
			}
			if z.AMap == nil {
				z.AMap = make(map[string]int, zb0007)
			} else if len(z.AMap) > 0 {
				clear(z.AMap)
			}
			for zb0007 > 0 {
				zb0007--
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AMap")
					return
				}
				var za0003 int
				za0003, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "AMap", za0002)
					return
				}
				z.AMap[za0002] = za0003
			}
			zb0001Mask |= 0x1000
		case "abin":
			z.ABin, err = dc.ReadBytes(z.ABin)
			if err != nil {
				err = msgp.WrapError(err, "ABin")
				return
			}
			zb0001Mask |= 0x2000
		case "aint":
			z.AInt, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "AInt")
				return
			}
			zb0001Mask |= 0x4000
		case "atring":
			z.AString, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "AString")
				return
			}
			zb0001Mask |= 0x8000
		case "adur":
			z.Adur, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "Adur")
				return
			}
			zb0001Mask |= 0x10000
		case "ajson":
			z.AJSON, err = dc.ReadJSONNumber()
			if err != nil {
				err = msgp.WrapError(err, "AJSON")
				return
			}
			zb0001Mask |= 0x20000
		case "anany":
			z.AnAny, err = dc.ReadIntf()
			if err != nil {
				err = msgp.WrapError(err, "AnAny")
				return
			}
			zb0001Mask |= 0x40000
		case "ozt":
			err = z.ClearOmittedTuple.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "ClearOmittedTuple")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7ffff {
		if (zb0001Mask & 0x1) == 0 {
			z.AStruct = ClearOmittedA{}
		}
		if (zb0001Mask & 0x2) == 0 {
			z.BStruct = ClearOmittedA{}
		}
		if (zb0001Mask & 0x4) == 0 {
			z.AStructPtr = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.BStructPtr = nil
		}
		if (zb0001Mask & 0x10) == 0 {
			z.AExt = OmitZeroExt{}
		}
		if (zb0001Mask & 0x20) == 0 {
			z.APtrNamedStr = nil
		}
		if (zb0001Mask & 0x40) == 0 {
			z.ANamedStruct = (NamedStructCO{})
		}
		if (zb0001Mask & 0x80) == 0 {
			z.APtrNamedStruct = nil
		}
		if (zb0001Mask & 0x100) == 0 {
			z.SomeEmbed = ""
		}
		if (zb0001Mask & 0x200) == 0 {
			z.EmbeddableStructCO2 = (EmbeddableStructCO2{})
		}
		if (zb0001Mask & 0x400) == 0 {
			z.ATime = (time.Time{})
		}
		if (zb0001Mask & 0x800) == 0 {
			z.ASlice = nil
		}
		if (zb0001Mask & 0x1000) == 0 {
			z.AMap = nil
		}
		if (zb0001Mask & 0x2000) == 0 {
			z.ABin = nil
		}
		if (zb0001Mask & 0x4000) == 0 {
			z.AInt = 0
		}
		if (zb0001Mask & 0x8000) == 0 {
			z.AString = ""
		}
		if (zb0001Mask & 0x10000) == 0 {
			z.Adur = 0
		}
		if (zb0001Mask & 0x20000) == 0 {
			z.AJSON = ""
		}
		if (zb0001Mask & 0x40000) == 0 {
			z.AnAny = nil
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ClearOmitted0) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(20)
	var zb0001Mask uint32 /* 20 bits */
	_ = zb0001Mask
	if z.BStruct.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.AStructPtr == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.BStructPtr.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.AExt.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.APtrNamedStr.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.ANamedStruct.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.APtrNamedStruct.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.SomeEmbed == "" {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.EmbeddableStructCO2.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.ATime.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.ASlice == nil {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.AMap == nil {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	if z.ABin == nil {
		zb0001Len--
		zb0001Mask |= 0x2000
	}
	if z.AInt == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000
	}
	if z.AString == "" {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	if z.Adur == 0 {
		zb0001Len--
		zb0001Mask |= 0x10000
	}
	if z.AJSON == "" {
		zb0001Len--
		zb0001Mask |= 0x20000
	}
	if z.AnAny == nil {
		zb0001Len--
		zb0001Mask |= 0x40000
	}
	// variable map header, size zb0001Len
	err = en.WriteMapHeader(zb0001Len)
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "astruct"
		err = en.Append(0xa7, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74)
		if err != nil {
			return
		}
		err = z.AStruct.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "AStruct")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "bstruct"
			err = en.Append(0xa7, 0x62, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74)
			if err != nil {
				return
			}
			err = z.BStruct.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "BStruct")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "astructptr"
			err = en.Append(0xaa, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x70, 0x74, 0x72)
			if err != nil {
				return
			}
			if z.AStructPtr == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.AStructPtr.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "AStructPtr")
					return
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "bstructptr"
			err = en.Append(0xaa, 0x62, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x70, 0x74, 0x72)
			if err != nil {
				return
			}
			if z.BStructPtr == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.BStructPtr.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "BStructPtr")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "aext"
			err = en.Append(0xa4, 0x61, 0x65, 0x78, 0x74)
			if err != nil {
				return
			}
			err = z.AExt.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "AExt")
				return
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "aptrnamedstr"
			err = en.Append(0xac, 0x61, 0x70, 0x74, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x73, 0x74, 0x72)
			if err != nil {
				return
			}
			if z.APtrNamedStr == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteString(string(*z.APtrNamedStr))
				if err != nil {
					err = msgp.WrapError(err, "APtrNamedStr")
					return
				}
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "anamedstruct"
			err = en.Append(0xac, 0x61, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74)
			if err != nil {
				return
			}
			// check for omitted fields
			zb0002Len := uint32(2)
			var zb0002Mask uint8 /* 2 bits */
			_ = zb0002Mask
			if z.ANamedStruct.A == "" {
				zb0002Len--
				zb0002Mask |= 0x1
			}
			if z.ANamedStruct.B == "" {
				zb0002Len--
				zb0002Mask |= 0x2
			}
			// variable map header, size zb0002Len
			err = en.Append(0x80 | uint8(zb0002Len))
			if err != nil {
				return
			}

			// skip if no fields are to be emitted
			if zb0002Len != 0 {
				if (zb0002Mask & 0x1) == 0 { // if not omitted
					// write "a"
					err = en.Append(0xa1, 0x61)
					if err != nil {
						return
					}
					err = en.WriteString(z.ANamedStruct.A)
					if err != nil {
						err = msgp.WrapError(err, "ANamedStruct", "A")
						return
					}
				}
				if (zb0002Mask & 0x2) == 0 { // if not omitted
					// write "b"
					err = en.Append(0xa1, 0x62)
					if err != nil {
						return
					}
					err = en.WriteString(z.ANamedStruct.B)
					if err != nil {
						err = msgp.WrapError(err, "ANamedStruct", "B")
						return
					}
				}
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "aptrnamedstruct"
			err = en.Append(0xaf, 0x61, 0x70, 0x74, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74)
			if err != nil {
				return
			}
			if z.APtrNamedStruct == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				// check for omitted fields
				zb0003Len := uint32(2)
				var zb0003Mask uint8 /* 2 bits */
				_ = zb0003Mask
				if z.APtrNamedStruct.A == "" {
					zb0003Len--
					zb0003Mask |= 0x1
				}
				if z.APtrNamedStruct.B == "" {
					zb0003Len--
					zb0003Mask |= 0x2
				}
				// variable map header, size zb0003Len
				err = en.Append(0x80 | uint8(zb0003Len))
				if err != nil {
					return
				}

				// skip if no fields are to be emitted
				if zb0003Len != 0 {
					if (zb0003Mask & 0x1) == 0 { // if not omitted
						// write "a"
						err = en.Append(0xa1, 0x61)
						if err != nil {
							return
						}
						err = en.WriteString(z.APtrNamedStruct.A)
						if err != nil {
							err = msgp.WrapError(err, "APtrNamedStruct", "A")
							return
						}
					}
					if (zb0003Mask & 0x2) == 0 { // if not omitted
						// write "b"
						err = en.Append(0xa1, 0x62)
						if err != nil {
							return
						}
						err = en.WriteString(z.APtrNamedStruct.B)
						if err != nil {
							err = msgp.WrapError(err, "APtrNamedStruct", "B")
							return
						}
					}
				}
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "someembed2"
			err = en.Append(0xaa, 0x73, 0x6f, 0x6d, 0x65, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x32)
			if err != nil {
				return
			}
			err = en.WriteString(z.SomeEmbed)
			if err != nil {
				err = msgp.WrapError(err, "SomeEmbed")
				return
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "embeddablestruct2"
			err = en.Append(0xb1, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x32)
			if err != nil {
				return
			}
			// check for omitted fields
			zb0004Len := uint32(1)
			var zb0004Mask uint8 /* 1 bits */
			_ = zb0004Mask
			if z.EmbeddableStructCO2.SomeEmbed2 == "" {
				zb0004Len--
				zb0004Mask |= 0x1
			}
			// variable map header, size zb0004Len
			err = en.Append(0x80 | uint8(zb0004Len))
			if err != nil {
				return
			}
			if (zb0004Mask & 0x1) == 0 { // if not omitted
				// write "someembed2"
				err = en.Append(0xaa, 0x73, 0x6f, 0x6d, 0x65, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x32)
				if err != nil {
					return
				}
				err = en.WriteString(z.EmbeddableStructCO2.SomeEmbed2)
				if err != nil {
					err = msgp.WrapError(err, "EmbeddableStructCO2", "SomeEmbed2")
					return
				}
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// write "atime"
			err = en.Append(0xa5, 0x61, 0x74, 0x69, 0x6d, 0x65)
			if err != nil {
				return
			}
			err = en.WriteTime(z.ATime)
			if err != nil {
				err = msgp.WrapError(err, "ATime")
				return
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// write "aslice"
			err = en.Append(0xa6, 0x61, 0x73, 0x6c, 0x69, 0x63, 0x65)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.ASlice)))
			if err != nil {
				err = msgp.WrapError(err, "ASlice")
				return
			}
			for za0001 := range z.ASlice {
				err = en.WriteInt(z.ASlice[za0001])
				if err != nil {
					err = msgp.WrapError(err, "ASlice", za0001)
					return
				}
			}
		}
		if (zb0001Mask & 0x1000) == 0 { // if not omitted
			// write "amap"
			err = en.Append(0xa4, 0x61, 0x6d, 0x61, 0x70)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.AMap)))
			if err != nil {
				err = msgp.WrapError(err, "AMap")
				return
			}
			for za0002, za0003 := range z.AMap {
				err = en.WriteString(za0002)
				if err != nil {
					err = msgp.WrapError(err, "AMap")
					return
				}
				err = en.WriteInt(za0003)
				if err != nil {
					err = msgp.WrapError(err, "AMap", za0002)
					return
				}
			}
		}
		if (zb0001Mask & 0x2000) == 0 { // if not omitted
			// write "abin"
			err = en.Append(0xa4, 0x61, 0x62, 0x69, 0x6e)
			if err != nil {
				return
			}
			err = en.WriteBytes(z.ABin)
			if err != nil {
				err = msgp.WrapError(err, "ABin")
				return
			}
		}
		if (zb0001Mask & 0x4000) == 0 { // if not omitted
			// write "aint"
			err = en.Append(0xa4, 0x61, 0x69, 0x6e, 0x74)
			if err != nil {
				return
			}
			err = en.WriteInt(z.AInt)
			if err != nil {
				err = msgp.WrapError(err, "AInt")
				return
			}
		}
		if (zb0001Mask & 0x8000) == 0 { // if not omitted
			// write "atring"
			err = en.Append(0xa6, 0x61, 0x74, 0x72, 0x69, 0x6e, 0x67)
			if err != nil {
				return
			}
			err = en.WriteString(z.AString)
			if err != nil {
				err = msgp.WrapError(err, "AString")
				return
			}
		}
		if (zb0001Mask & 0x10000) == 0 { // if not omitted
			// write "adur"
			err = en.Append(0xa4, 0x61, 0x64, 0x75, 0x72)
			if err != nil {
				return
			}
			err = en.WriteDuration(z.Adur)
			if err != nil {
				err = msgp.WrapError(err, "Adur")
				return
			}
		}
		if (zb0001Mask & 0x20000) == 0 { // if not omitted
			// write "ajson"
			err = en.Append(0xa5, 0x61, 0x6a, 0x73, 0x6f, 0x6e)
			if err != nil {
				return
			}
			err = en.WriteJSONNumber(z.AJSON)
			if err != nil {
				err = msgp.WrapError(err, "AJSON")
				return
			}
		}
		if (zb0001Mask & 0x40000) == 0 { // if not omitted
			// write "anany"
			err = en.Append(0xa5, 0x61, 0x6e, 0x61, 0x6e, 0x79)
			if err != nil {
				return
			}
			err = en.WriteIntf(z.AnAny)
			if err != nil {
				err = msgp.WrapError(err, "AnAny")
				return
			}
		}
		// write "ozt"
		err = en.Append(0xa3, 0x6f, 0x7a, 0x74)
		if err != nil {
			return
		}
		err = z.ClearOmittedTuple.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "ClearOmittedTuple")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ClearOmitted0) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(20)
	var zb0001Mask uint32 /* 20 bits */
	_ = zb0001Mask
	if z.BStruct.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.AStructPtr == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.BStructPtr.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.AExt.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.APtrNamedStr.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.ANamedStruct.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.APtrNamedStruct.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.SomeEmbed == "" {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.EmbeddableStructCO2.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.ATime.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.ASlice == nil {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.AMap == nil {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	if z.ABin == nil {
		zb0001Len--
		zb0001Mask |= 0x2000
	}
	if z.AInt == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000
	}
	if z.AString == "" {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	if z.Adur == 0 {
		zb0001Len--
		zb0001Mask |= 0x10000
	}
	if z.AJSON == "" {
		zb0001Len--
		zb0001Mask |= 0x20000
	}
	if z.AnAny == nil {
		zb0001Len--
		zb0001Mask |= 0x40000
	}
	// variable map header, size zb0001Len
	o = msgp.AppendMapHeader(o, zb0001Len)

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "astruct"
		o = append(o, 0xa7, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74)
		o, err = z.AStruct.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "AStruct")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "bstruct"
			o = append(o, 0xa7, 0x62, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74)
			o, err = z.BStruct.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "BStruct")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "astructptr"
			o = append(o, 0xaa, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x70, 0x74, 0x72)
			if z.AStructPtr == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.AStructPtr.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "AStructPtr")
					return
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "bstructptr"
			o = append(o, 0xaa, 0x62, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x70, 0x74, 0x72)
			if z.BStructPtr == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.BStructPtr.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "BStructPtr")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "aext"
			o = append(o, 0xa4, 0x61, 0x65, 0x78, 0x74)
			o, err = z.AExt.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "AExt")
				return
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "aptrnamedstr"
			o = append(o, 0xac, 0x61, 0x70, 0x74, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x73, 0x74, 0x72)
			if z.APtrNamedStr == nil {
				o = msgp.AppendNil(o)
			} else {
				o = msgp.AppendString(o, string(*z.APtrNamedStr))
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "anamedstruct"
			o = append(o, 0xac, 0x61, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74)
			// check for omitted fields
			zb0002Len := uint32(2)
			var zb0002Mask uint8 /* 2 bits */
			_ = zb0002Mask
			if z.ANamedStruct.A == "" {
				zb0002Len--
				zb0002Mask |= 0x1
			}
			if z.ANamedStruct.B == "" {
				zb0002Len--
				zb0002Mask |= 0x2
			}
			// variable map header, size zb0002Len
			o = append(o, 0x80|uint8(zb0002Len))

			// skip if no fields are to be emitted
			if zb0002Len != 0 {
				if (zb0002Mask & 0x1) == 0 { // if not omitted
					// string "a"
					o = append(o, 0xa1, 0x61)
					o = msgp.AppendString(o, z.ANamedStruct.A)
				}
				if (zb0002Mask & 0x2) == 0 { // if not omitted
					// string "b"
					o = append(o, 0xa1, 0x62)
					o = msgp.AppendString(o, z.ANamedStruct.B)
				}
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "aptrnamedstruct"
			o = append(o, 0xaf, 0x61, 0x70, 0x74, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74)
			if z.APtrNamedStruct == nil {
				o = msgp.AppendNil(o)
			} else {
				// check for omitted fields
				zb0003Len := uint32(2)
				var zb0003Mask uint8 /* 2 bits */
				_ = zb0003Mask
				if z.APtrNamedStruct.A == "" {
					zb0003Len--
					zb0003Mask |= 0x1
				}
				if z.APtrNamedStruct.B == "" {
					zb0003Len--
					zb0003Mask |= 0x2
				}
				// variable map header, size zb0003Len
				o = append(o, 0x80|uint8(zb0003Len))

				// skip if no fields are to be emitted
				if zb0003Len != 0 {
					if (zb0003Mask & 0x1) == 0 { // if not omitted
						// string "a"
						o = append(o, 0xa1, 0x61)
						o = msgp.AppendString(o, z.APtrNamedStruct.A)
					}
					if (zb0003Mask & 0x2) == 0 { // if not omitted
						// string "b"
						o = append(o, 0xa1, 0x62)
						o = msgp.AppendString(o, z.APtrNamedStruct.B)
					}
				}
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "someembed2"
			o = append(o, 0xaa, 0x73, 0x6f, 0x6d, 0x65, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x32)
			o = msgp.AppendString(o, z.SomeEmbed)
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// string "embeddablestruct2"
			o = append(o, 0xb1, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x32)
			// check for omitted fields
			zb0004Len := uint32(1)
			var zb0004Mask uint8 /* 1 bits */
			_ = zb0004Mask
			if z.EmbeddableStructCO2.SomeEmbed2 == "" {
				zb0004Len--
				zb0004Mask |= 0x1
			}
			// variable map header, size zb0004Len
			o = append(o, 0x80|uint8(zb0004Len))
			if (zb0004Mask & 0x1) == 0 { // if not omitted
				// string "someembed2"
				o = append(o, 0xaa, 0x73, 0x6f, 0x6d, 0x65, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x32)
				o = msgp.AppendString(o, z.EmbeddableStructCO2.SomeEmbed2)
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// string "atime"
			o = append(o, 0xa5, 0x61, 0x74, 0x69, 0x6d, 0x65)
			o = msgp.AppendTime(o, z.ATime)
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// string "aslice"
			o = append(o, 0xa6, 0x61, 0x73, 0x6c, 0x69, 0x63, 0x65)
			o = msgp.AppendArrayHeader(o, uint32(len(z.ASlice)))
			for za0001 := range z.ASlice {
				o = msgp.AppendInt(o, z.ASlice[za0001])
			}
		}
		if (zb0001Mask & 0x1000) == 0 { // if not omitted
			// string "amap"
			o = append(o, 0xa4, 0x61, 0x6d, 0x61, 0x70)
			o = msgp.AppendMapHeader(o, uint32(len(z.AMap)))
			for za0002, za0003 := range z.AMap {
				o = msgp.AppendString(o, za0002)
				o = msgp.AppendInt(o, za0003)
			}
		}
		if (zb0001Mask & 0x2000) == 0 { // if not omitted
			// string "abin"
			o = append(o, 0xa4, 0x61, 0x62, 0x69, 0x6e)
			o = msgp.AppendBytes(o, z.ABin)
		}
		if (zb0001Mask & 0x4000) == 0 { // if not omitted
			// string "aint"
			o = append(o, 0xa4, 0x61, 0x69, 0x6e, 0x74)
			o = msgp.AppendInt(o, z.AInt)
		}
		if (zb0001Mask & 0x8000) == 0 { // if not omitted
			// string "atring"
			o = append(o, 0xa6, 0x61, 0x74, 0x72, 0x69, 0x6e, 0x67)
			o = msgp.AppendString(o, z.AString)
		}
		if (zb0001Mask & 0x10000) == 0 { // if not omitted
			// string "adur"
			o = append(o, 0xa4, 0x61, 0x64, 0x75, 0x72)
			o = msgp.AppendDuration(o, z.Adur)
		}
		if (zb0001Mask & 0x20000) == 0 { // if not omitted
			// string "ajson"
			o = append(o, 0xa5, 0x61, 0x6a, 0x73, 0x6f, 0x6e)
			o, err = msgp.AppendJSONNumber(o, z.AJSON)
			if err != nil {
				err = msgp.WrapError(err, "AJSON")
				return
			}
		}
		if (zb0001Mask & 0x40000) == 0 { // if not omitted
			// string "anany"
			o = append(o, 0xa5, 0x61, 0x6e, 0x61, 0x6e, 0x79)
			o, err = msgp.AppendIntf(o, z.AnAny)
			if err != nil {
				err = msgp.WrapError(err, "AnAny")
				return
			}
		}
		// string "ozt"
		o = append(o, 0xa3, 0x6f, 0x7a, 0x74)
		o, err = z.ClearOmittedTuple.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "ClearOmittedTuple")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ClearOmitted0) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint32 /* 19 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "astruct":
			bts, err = z.AStruct.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "AStruct")
				return
			}
			zb0001Mask |= 0x1
		case "bstruct":
			bts, err = z.BStruct.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "BStruct")
				return
			}
			zb0001Mask |= 0x2
		case "astructptr":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AStructPtr = nil
			} else {
				if z.AStructPtr == nil {
					z.AStructPtr = new(ClearOmittedA)
				}
				bts, err = z.AStructPtr.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "AStructPtr")
					return
				}
			}
			zb0001Mask |= 0x4
		case "bstructptr":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.BStructPtr = nil
			} else {
				if z.BStructPtr == nil {
					z.BStructPtr = new(ClearOmittedA)
				}
				bts, err = z.BStructPtr.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "BStructPtr")
					return
				}
			}
			zb0001Mask |= 0x8
		case "aext":
			bts, err = z.AExt.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "AExt")
				return
			}
			zb0001Mask |= 0x10
		case "aptrnamedstr":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.APtrNamedStr = nil
			} else {
				if z.APtrNamedStr == nil {
					z.APtrNamedStr = new(NamedStringCO)
				}
				{
					var zb0002 string
					zb0002, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "APtrNamedStr")
						return
					}
					*z.APtrNamedStr = NamedStringCO(zb0002)
				}
			}
			zb0001Mask |= 0x20
		case "anamedstruct":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ANamedStruct")
				return
			}
			var zb0003Mask uint8 /* 2 bits */
			_ = zb0003Mask
			for zb0003 > 0 {
				zb0003--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "ANamedStruct")
					return
				}
				switch msgp.UnsafeString(field) {
				case "a":
					z.ANamedStruct.A, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "ANamedStruct", "A")
						return
					}
					zb0003Mask |= 0x1
				case "b":
					z.ANamedStruct.B, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "ANamedStruct", "B")
						return
					}
					zb0003Mask |= 0x2
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "ANamedStruct")
						return
					}
				}
			}
			// Clear omitted fields.
			if zb0003Mask != 0x3 {
				if (zb0003Mask & 0x1) == 0 {
					z.ANamedStruct.A = ""
				}
				if (zb0003Mask & 0x2) == 0 {
					z.ANamedStruct.B = ""
				}
			}
			zb0001Mask |= 0x40
		case "aptrnamedstruct":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.APtrNamedStruct = nil
			} else {
				if z.APtrNamedStruct == nil {
					z.APtrNamedStruct = new(NamedStructCO)
				}
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "APtrNamedStruct")
					return
				}
				var zb0004Mask uint8 /* 2 bits */
				_ = zb0004Mask
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "APtrNamedStruct")
						return
					}
					switch msgp.UnsafeString(field) {
					case "a":
						z.APtrNamedStruct.A, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "APtrNamedStruct", "A")
							return
						}
						zb0004Mask |= 0x1
					case "b":
						z.APtrNamedStruct.B, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "APtrNamedStruct", "B")
							return
						}
						zb0004Mask |= 0x2
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "APtrNamedStruct")
							return
						}
					}
				}
				// Clear omitted fields.
				if zb0004Mask != 0x3 {
					if (zb0004Mask & 0x1) == 0 {
						z.APtrNamedStruct.A = ""
					}
					if (zb0004Mask & 0x2) == 0 {
						z.APtrNamedStruct.B = ""
					}
				}
			}
			zb0001Mask |= 0x80
		case "someembed2":
			z.SomeEmbed, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SomeEmbed")
				return
			}
			zb0001Mask |= 0x100
		case "embeddablestruct2":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EmbeddableStructCO2")
				return
			}
			var zb0005Mask uint8 /* 1 bits */
			_ = zb0005Mask
			for zb0005 > 0 {
				zb0005--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "EmbeddableStructCO2")
					return
				}
				switch msgp.UnsafeString(field) {
				case "someembed2":
					z.EmbeddableStructCO2.SomeEmbed2, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "EmbeddableStructCO2", "SomeEmbed2")
						return
					}
					zb0005Mask |= 0x1
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "EmbeddableStructCO2")
						return
					}
				}
			}
			// Clear omitted fields.
			if (zb0005Mask & 0x1) == 0 {
				z.EmbeddableStructCO2.SomeEmbed2 = ""
			}

			zb0001Mask |= 0x200
		case "atime":
			z.ATime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ATime")
				return
			}
			zb0001Mask |= 0x400
		case "aslice":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ASlice")
				return
			}
			if cap(z.ASlice) >= int(zb0006) {
				z.ASlice = (z.ASlice)[:zb0006]
			} else {
				z.ASlice = make([]int, zb0006)
			}
			for za0001 := range z.ASlice {
				z.ASlice[za0001], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ASlice", za0001)
					return
				}
			}
			zb0001Mask |= 0x800
		case "amap":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AMap")
				return
			}
			if z.AMap == nil {
				z.AMap = make(map[string]int, zb0007)
			} else if len(z.AMap) > 0 {
				clear(z.AMap)
			}
			for zb0007 > 0 {
				var za0003 int
				zb0007--
				var za0002 string
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AMap")
					return
				}
				za0003, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AMap", za0002)
					return
				}
				z.AMap[za0002] = za0003
			}
			zb0001Mask |= 0x1000
		case "abin":
			z.ABin, bts, err = msgp.ReadBytesBytes(bts, z.ABin)
			if err != nil {
				err = msgp.WrapError(err, "ABin")
				return
			}
			zb0001Mask |= 0x2000
		case "aint":
			z.AInt, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AInt")
				return
			}
			zb0001Mask |= 0x4000
		case "atring":
			z.AString, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AString")
				return
			}
			zb0001Mask |= 0x8000
		case "adur":
			z.Adur, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Adur")
				return
			}
			zb0001Mask |= 0x10000
		case "ajson":
			z.AJSON, bts, err = msgp.ReadJSONNumberBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AJSON")
				return
			}
			zb0001Mask |= 0x20000
		case "anany":
			z.AnAny, bts, err = msgp.ReadIntfBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AnAny")
				return
			}
			zb0001Mask |= 0x40000
		case "ozt":
			bts, err = z.ClearOmittedTuple.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "ClearOmittedTuple")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7ffff {
		if (zb0001Mask & 0x1) == 0 {
			z.AStruct = ClearOmittedA{}
		}
		if (zb0001Mask & 0x2) == 0 {
			z.BStruct = ClearOmittedA{}
		}
		if (zb0001Mask & 0x4) == 0 {
			z.AStructPtr = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.BStructPtr = nil
		}
		if (zb0001Mask & 0x10) == 0 {
			z.AExt = OmitZeroExt{}
		}
		if (zb0001Mask & 0x20) == 0 {
			z.APtrNamedStr = nil
		}
		if (zb0001Mask & 0x40) == 0 {
			z.ANamedStruct = (NamedStructCO{})
		}
		if (zb0001Mask & 0x80) == 0 {
			z.APtrNamedStruct = nil
		}
		if (zb0001Mask & 0x100) == 0 {
			z.SomeEmbed = ""
		}
		if (zb0001Mask & 0x200) == 0 {
			z.EmbeddableStructCO2 = (EmbeddableStructCO2{})
		}
		if (zb0001Mask & 0x400) == 0 {
			z.ATime = (time.Time{})
		}
		if (zb0001Mask & 0x800) == 0 {
			z.ASlice = nil
		}
		if (zb0001Mask & 0x1000) == 0 {
			z.AMap = nil
		}
		if (zb0001Mask & 0x2000) == 0 {
			z.ABin = nil
		}
		if (zb0001Mask & 0x4000) == 0 {
			z.AInt = 0
		}
		if (zb0001Mask & 0x8000) == 0 {
			z.AString = ""
		}
		if (zb0001Mask & 0x10000) == 0 {
			z.Adur = 0
		}
		if (zb0001Mask & 0x20000) == 0 {
			z.AJSON = ""
		}
		if (zb0001Mask & 0x40000) == 0 {
			z.AnAny = nil
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ClearOmitted0) Msgsize() (s int) {
	s = 3 + 8 + z.AStruct.Msgsize() + 8 + z.BStruct.Msgsize() + 11
	if z.AStructPtr == nil {
		s += msgp.NilSize
	} else {
		s += z.AStructPtr.Msgsize()
	}
	s += 11
	if z.BStructPtr == nil {
		s += msgp.NilSize
	} else {
		s += z.BStructPtr.Msgsize()
	}
	s += 5 + z.AExt.Msgsize() + 13
	if z.APtrNamedStr == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(string(*z.APtrNamedStr))
	}
	s += 13 + 1 + 2 + msgp.StringPrefixSize + len(z.ANamedStruct.A) + 2 + msgp.StringPrefixSize + len(z.ANamedStruct.B) + 16
	if z.APtrNamedStruct == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 2 + msgp.StringPrefixSize + len(z.APtrNamedStruct.A) + 2 + msgp.StringPrefixSize + len(z.APtrNamedStruct.B)
	}
	s += 11 + msgp.StringPrefixSize + len(z.SomeEmbed) + 18 + 1 + 11 + msgp.StringPrefixSize + len(z.EmbeddableStructCO2.SomeEmbed2) + 6 + msgp.TimeSize + 7 + msgp.ArrayHeaderSize + (len(z.ASlice) * (msgp.IntSize)) + 5 + msgp.MapHeaderSize
	if z.AMap != nil {
		for za0002, za0003 := range z.AMap {
			_ = za0003
			s += msgp.StringPrefixSize + len(za0002) + msgp.IntSize
		}
	}
	s += 5 + msgp.BytesPrefixSize + len(z.ABin) + 5 + msgp.IntSize + 7 + msgp.StringPrefixSize + len(z.AString) + 5 + msgp.DurationSize + 6 + msgp.JSONNumberSize + 6 + msgp.GuessSize(z.AnAny) + 4 + z.ClearOmittedTuple.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ClearOmitted1) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "t1":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "T1")
				return
			}
			if zb0002 != 3 {
				err = msgp.ArrayError{Wanted: 3, Got: zb0002}
				return
			}
			z.T1.FieldA, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "T1", "FieldA")
				return
			}
			{
				var zb0003 string
				zb0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "T1", "FieldB")
					return
				}
				z.T1.FieldB = NamedStringCO(zb0003)
			}
			{
				var zb0004 string
				zb0004, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "T1", "FieldC")
					return
				}
				z.T1.FieldC = NamedStringCO(zb0004)
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ClearOmitted1) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "t1"
	err = en.Append(0x81, 0xa2, 0x74, 0x31)
	if err != nil {
		return
	}
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = en.WriteString(z.T1.FieldA)
	if err != nil {
		err = msgp.WrapError(err, "T1", "FieldA")
		return
	}
	err = en.WriteString(string(z.T1.FieldB))
	if err != nil {
		err = msgp.WrapError(err, "T1", "FieldB")
		return
	}
	err = en.WriteString(string(z.T1.FieldC))
	if err != nil {
		err = msgp.WrapError(err, "T1", "FieldC")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ClearOmitted1) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "t1"
	o = append(o, 0x81, 0xa2, 0x74, 0x31)
	// array header, size 3
	o = append(o, 0x93)
	o = msgp.AppendString(o, z.T1.FieldA)
	o = msgp.AppendString(o, string(z.T1.FieldB))
	o = msgp.AppendString(o, string(z.T1.FieldC))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ClearOmitted1) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "t1":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "T1")
				return
			}
			if zb0002 != 3 {
				err = msgp.ArrayError{Wanted: 3, Got: zb0002}
				return
			}
			z.T1.FieldA, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "T1", "FieldA")
				return
			}
			{
				var zb0003 string
				zb0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "T1", "FieldB")
					return
				}
				z.T1.FieldB = NamedStringCO(zb0003)
			}
			{
				var zb0004 string
				zb0004, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "T1", "FieldC")
					return
				}
				z.T1.FieldC = NamedStringCO(zb0004)
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ClearOmitted1) Msgsize() (s int) {
	s = 1 + 3 + 1 + msgp.StringPrefixSize + len(z.T1.FieldA) + msgp.StringPrefixSize + len(string(z.T1.FieldB)) + msgp.StringPrefixSize + len(string(z.T1.FieldC))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ClearOmittedA) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "a":
			z.A, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "A")
				return
			}
			zb0001Mask |= 0x1
		case "b":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "B")
					return
				}
				z.B = NamedStringCO(zb0002)
			}
			zb0001Mask |= 0x2
		case "c":
			{
				var zb0003 string
				zb0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "C")
					return
				}
				z.C = NamedStringCO(zb0003)
			}
			zb0001Mask |= 0x4
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7 {
		if (zb0001Mask & 0x1) == 0 {
			z.A = ""
		}
		if (zb0001Mask & 0x2) == 0 {
			z.B = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.C = ""
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ClearOmittedA) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.A == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.B.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.C.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "a"
			err = en.Append(0xa1, 0x61)
			if err != nil {
				return
			}
			err = en.WriteString(z.A)
			if err != nil {
				err = msgp.WrapError(err, "A")
				return
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "b"
			err = en.Append(0xa1, 0x62)
			if err != nil {
				return
			}
			err = en.WriteString(string(z.B))
			if err != nil {
				err = msgp.WrapError(err, "B")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "c"
			err = en.Append(0xa1, 0x63)
			if err != nil {
				return
			}
			err = en.WriteString(string(z.C))
			if err != nil {
				err = msgp.WrapError(err, "C")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ClearOmittedA) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.A == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.B.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.C.IsZero() {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "a"
			o = append(o, 0xa1, 0x61)
			o = msgp.AppendString(o, z.A)
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "b"
			o = append(o, 0xa1, 0x62)
			o = msgp.AppendString(o, string(z.B))
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "c"
			o = append(o, 0xa1, 0x63)
			o = msgp.AppendString(o, string(z.C))
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ClearOmittedA) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "a":
			z.A, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A")
				return
			}
			zb0001Mask |= 0x1
		case "b":
			{
				var zb0002 string
				zb0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "B")
					return
				}
				z.B = NamedStringCO(zb0002)
			}
			zb0001Mask |= 0x2
		case "c":
			{
				var zb0003 string
				zb0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "C")
					return
				}
				z.C = NamedStringCO(zb0003)
			}
			zb0001Mask |= 0x4
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7 {
		if (zb0001Mask & 0x1) == 0 {
			z.A = ""
		}
		if (zb0001Mask & 0x2) == 0 {
			z.B = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.C = ""
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ClearOmittedA) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.A) + 2 + msgp.StringPrefixSize + len(string(z.B)) + 2 + msgp.StringPrefixSize + len(string(z.C))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ClearOmittedTuple) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	z.FieldA, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "FieldA")
		return
	}
	{
		var zb0002 string
		zb0002, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, "FieldB")
			return
		}
		z.FieldB = NamedStringCO(zb0002)
	}
	{
		var zb0003 string
		zb0003, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, "FieldC")
			return
		}
		z.FieldC = NamedStringCO(zb0003)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ClearOmittedTuple) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = en.WriteString(z.FieldA)
	if err != nil {
		err = msgp.WrapError(err, "FieldA")
		return
	}
	err = en.WriteString(string(z.FieldB))
	if err != nil {
		err = msgp.WrapError(err, "FieldB")
		return
	}
	err = en.WriteString(string(z.FieldC))
	if err != nil {
		err = msgp.WrapError(err, "FieldC")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ClearOmittedTuple) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	o = msgp.AppendString(o, z.FieldA)
	o = msgp.AppendString(o, string(z.FieldB))
	o = msgp.AppendString(o, string(z.FieldC))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ClearOmittedTuple) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	z.FieldA, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "FieldA")
		return
	}
	{
		var zb0002 string
		zb0002, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "FieldB")
			return
		}
		z.FieldB = NamedStringCO(zb0002)
	}
	{
		var zb0003 string
		zb0003, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "FieldC")
			return
		}
		z.FieldC = NamedStringCO(zb0003)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ClearOmittedTuple) Msgsize() (s int) {
	s = 1 + msgp.StringPrefixSize + len(z.FieldA) + msgp.StringPrefixSize + len(string(z.FieldB)) + msgp.StringPrefixSize + len(string(z.FieldC))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EmbeddableStructCO) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "someembed2":
			z.SomeEmbed, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SomeEmbed")
				return
			}
			zb0001Mask |= 0x1
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if (zb0001Mask & 0x1) == 0 {
		z.SomeEmbed = ""
	}

	return
}

// EncodeMsg implements msgp.Encodable
func (z EmbeddableStructCO) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	if z.SomeEmbed == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not omitted
		// write "someembed2"
		err = en.Append(0xaa, 0x73, 0x6f, 0x6d, 0x65, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x32)
		if err != nil {
			return
		}
		err = en.WriteString(z.SomeEmbed)
		if err != nil {
			err = msgp.WrapError(err, "SomeEmbed")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z EmbeddableStructCO) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	if z.SomeEmbed == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if (zb0001Mask & 0x1) == 0 { // if not omitted
		// string "someembed2"
		o = append(o, 0xaa, 0x73, 0x6f, 0x6d, 0x65, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x32)
		o = msgp.AppendString(o, z.SomeEmbed)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EmbeddableStructCO) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "someembed2":
			z.SomeEmbed, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SomeEmbed")
				return
			}
			zb0001Mask |= 0x1
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if (zb0001Mask & 0x1) == 0 {
		z.SomeEmbed = ""
	}

	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z EmbeddableStructCO) Msgsize() (s int) {
	s = 1 + 11 + msgp.StringPrefixSize + len(z.SomeEmbed)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EmbeddableStructCO2) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "someembed2":
			z.SomeEmbed2, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SomeEmbed2")
				return
			}
			zb0001Mask |= 0x1
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if (zb0001Mask & 0x1) == 0 {
		z.SomeEmbed2 = ""
	}

	return
}

// EncodeMsg implements msgp.Encodable
func (z EmbeddableStructCO2) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	if z.SomeEmbed2 == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not omitted
		// write "someembed2"
		err = en.Append(0xaa, 0x73, 0x6f, 0x6d, 0x65, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x32)
		if err != nil {
			return
		}
		err = en.WriteString(z.SomeEmbed2)
		if err != nil {
			err = msgp.WrapError(err, "SomeEmbed2")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z EmbeddableStructCO2) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	if z.SomeEmbed2 == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if (zb0001Mask & 0x1) == 0 { // if not omitted
		// string "someembed2"
		o = append(o, 0xaa, 0x73, 0x6f, 0x6d, 0x65, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x32)
		o = msgp.AppendString(o, z.SomeEmbed2)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EmbeddableStructCO2) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "someembed2":
			z.SomeEmbed2, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SomeEmbed2")
				return
			}
			zb0001Mask |= 0x1
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if (zb0001Mask & 0x1) == 0 {
		z.SomeEmbed2 = ""
	}

	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z EmbeddableStructCO2) Msgsize() (s int) {
	s = 1 + 11 + msgp.StringPrefixSize + len(z.SomeEmbed2)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NamedStringCO) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = NamedStringCO(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NamedStringCO) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(string(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NamedStringCO) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, string(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NamedStringCO) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = NamedStringCO(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NamedStringCO) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(string(z))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NamedStructCO) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "a":
			z.A, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "A")
				return
			}
			zb0001Mask |= 0x1
		case "b":
			z.B, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "B")
				return
			}
			zb0001Mask |= 0x2
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3 {
		if (zb0001Mask & 0x1) == 0 {
			z.A = ""
		}
		if (zb0001Mask & 0x2) == 0 {
			z.B = ""
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NamedStructCO) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	if z.A == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.B == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "a"
			err = en.Append(0xa1, 0x61)
			if err != nil {
				return
			}
			err = en.WriteString(z.A)
			if err != nil {
				err = msgp.WrapError(err, "A")
				return
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "b"
			err = en.Append(0xa1, 0x62)
			if err != nil {
				return
			}
			err = en.WriteString(z.B)
			if err != nil {
				err = msgp.WrapError(err, "B")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NamedStructCO) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	if z.A == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.B == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "a"
			o = append(o, 0xa1, 0x61)
			o = msgp.AppendString(o, z.A)
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "b"
			o = append(o, 0xa1, 0x62)
			o = msgp.AppendString(o, z.B)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NamedStructCO) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "a":
			z.A, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A")
				return
			}
			zb0001Mask |= 0x1
		case "b":
			z.B, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "B")
				return
			}
			zb0001Mask |= 0x2
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3 {
		if (zb0001Mask & 0x1) == 0 {
			z.A = ""
		}
		if (zb0001Mask & 0x2) == 0 {
			z.B = ""
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NamedStructCO) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.A) + 2 + msgp.StringPrefixSize + len(z.B)
	return
}
