// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ConvertErr) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Err":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Err")
					return
				}
				z.Err, err = toConvertErrVal(zb0002)
			}
			if err != nil {
				err = msgp.WrapError(err, "Err")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ConvertErr) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Err"
	err = en.Append(0x81, 0xa3, 0x45, 0x72, 0x72)
	if err != nil {
		return
	}
	var zb0002 string
	zb0002, err = fromConvertErrVal(z.Err)
	if err != nil {
		err = msgp.WrapError(err, "Err")
		return
	}
	err = en.WriteString(zb0002)
	if err != nil {
		err = msgp.WrapError(err, "Err")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ConvertErr) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Err"
	o = append(o, 0x81, 0xa3, 0x45, 0x72, 0x72)
	var zb0002 string
	zb0002, err = fromConvertErrVal(z.Err)
	if err != nil {
		err = msgp.WrapError(err, "Err")
		return
	}
	o = msgp.AppendString(o, zb0002)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConvertErr) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Err":
			{
				var zb0002 string
				zb0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Err")
					return
				}
				z.Err, err = toConvertErrVal(zb0002)

				if err != nil {
					err = msgp.WrapError(err, "Err")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ConvertErr) Msgsize() (s int) {
	s = 1 + 4
	var zb0001 string
	_ = z.Err
	s += msgp.StringPrefixSize + len(zb0001)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConvertIntf) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Intf":
			{
				var zb0002 interface{}
				zb0002, err = dc.ReadIntf()
				if err != nil {
					err = msgp.WrapError(err, "Intf")
					return
				}
				z.Intf, err = toConvertIntfVal(zb0002)
			}
			if err != nil {
				err = msgp.WrapError(err, "Intf")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ConvertIntf) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Intf"
	err = en.Append(0x81, 0xa4, 0x49, 0x6e, 0x74, 0x66)
	if err != nil {
		return
	}
	var zb0002 interface{}
	zb0002, err = fromConvertIntfVal(z.Intf)
	if err != nil {
		err = msgp.WrapError(err, "Intf")
		return
	}
	err = en.WriteIntf(zb0002)
	if err != nil {
		err = msgp.WrapError(err, "Intf")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ConvertIntf) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Intf"
	o = append(o, 0x81, 0xa4, 0x49, 0x6e, 0x74, 0x66)
	var zb0002 interface{}
	zb0002, err = fromConvertIntfVal(z.Intf)
	if err != nil {
		err = msgp.WrapError(err, "Intf")
		return
	}
	o, err = msgp.AppendIntf(o, zb0002)
	if err != nil {
		err = msgp.WrapError(err, "Intf")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConvertIntf) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Intf":
			{
				var zb0002 interface{}
				zb0002, bts, err = msgp.ReadIntfBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Intf")
					return
				}
				z.Intf, err = toConvertIntfVal(zb0002)

				if err != nil {
					err = msgp.WrapError(err, "Intf")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ConvertIntf) Msgsize() (s int) {
	s = 1 + 5
	var zb0001 interface{}
	_ = z.Intf
	s += msgp.GuessSize(zb0001)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConvertString) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "String":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "String")
					return
				}
				z.String, err = toConvertStringVal(zb0002)
			}
			if err != nil {
				err = msgp.WrapError(err, "String")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ConvertString) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "String"
	err = en.Append(0x81, 0xa6, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	var zb0002 string
	zb0002, err = fromConvertStringVal(z.String)
	if err != nil {
		err = msgp.WrapError(err, "String")
		return
	}
	err = en.WriteString(zb0002)
	if err != nil {
		err = msgp.WrapError(err, "String")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ConvertString) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "String"
	o = append(o, 0x81, 0xa6, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67)
	var zb0002 string
	zb0002, err = fromConvertStringVal(z.String)
	if err != nil {
		err = msgp.WrapError(err, "String")
		return
	}
	o = msgp.AppendString(o, zb0002)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConvertString) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "String":
			{
				var zb0002 string
				zb0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "String")
					return
				}
				z.String, err = toConvertStringVal(zb0002)

				if err != nil {
					err = msgp.WrapError(err, "String")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ConvertString) Msgsize() (s int) {
	s = 1 + 7
	var zb0001 string
	_ = z.String
	s += msgp.StringPrefixSize + len(zb0001)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConvertStringMapValue) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Strings":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Strings")
				return
			}
			if z.Strings == nil {
				z.Strings = make(map[string]ConvertStringVal, zb0002)
			} else if len(z.Strings) > 0 {
				clear(z.Strings)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Strings")
					return
				}
				var za0002 ConvertStringVal
				{
					var zb0003 string
					zb0003, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Strings", za0001)
						return
					}
					za0002, err = toConvertStringVal(zb0003)
				}
				if err != nil {
					err = msgp.WrapError(err, "Strings", za0001)
					return
				}
				z.Strings[za0001] = za0002
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ConvertStringMapValue) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Strings"
	err = en.Append(0x81, 0xa7, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Strings)))
	if err != nil {
		err = msgp.WrapError(err, "Strings")
		return
	}
	for za0001, za0002 := range z.Strings {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Strings")
			return
		}
		var zb0002 string
		zb0002, err = fromConvertStringVal(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Strings", za0001)
			return
		}
		err = en.WriteString(zb0002)
		if err != nil {
			err = msgp.WrapError(err, "Strings", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ConvertStringMapValue) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Strings"
	o = append(o, 0x81, 0xa7, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Strings)))
	for za0001, za0002 := range z.Strings {
		o = msgp.AppendString(o, za0001)
		var zb0002 string
		zb0002, err = fromConvertStringVal(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Strings", za0001)
			return
		}
		o = msgp.AppendString(o, zb0002)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConvertStringMapValue) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Strings":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Strings")
				return
			}
			if z.Strings == nil {
				z.Strings = make(map[string]ConvertStringVal, zb0002)
			} else if len(z.Strings) > 0 {
				clear(z.Strings)
			}
			for zb0002 > 0 {
				var za0002 ConvertStringVal
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Strings")
					return
				}
				{
					var zb0003 string
					zb0003, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Strings", za0001)
						return
					}
					za0002, err = toConvertStringVal(zb0003)

					if err != nil {
						err = msgp.WrapError(err, "Strings", za0001)
						return
					}
				}
				z.Strings[za0001] = za0002
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ConvertStringMapValue) Msgsize() (s int) {
	s = 1 + 8 + msgp.MapHeaderSize
	if z.Strings != nil {
		for za0001, za0002 := range z.Strings {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001)
			var zb0001 string
			_ = za0002
			s += msgp.StringPrefixSize + len(zb0001)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConvertStringSlice) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Strings":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Strings")
				return
			}
			if cap(z.Strings) >= int(zb0002) {
				z.Strings = (z.Strings)[:zb0002]
			} else {
				z.Strings = make([]ConvertStringVal, zb0002)
			}
			for za0001 := range z.Strings {
				{
					var zb0003 string
					zb0003, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Strings", za0001)
						return
					}
					z.Strings[za0001], err = toConvertStringVal(zb0003)
				}
				if err != nil {
					err = msgp.WrapError(err, "Strings", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ConvertStringSlice) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Strings"
	err = en.Append(0x81, 0xa7, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Strings)))
	if err != nil {
		err = msgp.WrapError(err, "Strings")
		return
	}
	for za0001 := range z.Strings {
		var zb0002 string
		zb0002, err = fromConvertStringVal(z.Strings[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Strings", za0001)
			return
		}
		err = en.WriteString(zb0002)
		if err != nil {
			err = msgp.WrapError(err, "Strings", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ConvertStringSlice) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Strings"
	o = append(o, 0x81, 0xa7, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Strings)))
	for za0001 := range z.Strings {
		var zb0002 string
		zb0002, err = fromConvertStringVal(z.Strings[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Strings", za0001)
			return
		}
		o = msgp.AppendString(o, zb0002)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConvertStringSlice) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Strings":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Strings")
				return
			}
			if cap(z.Strings) >= int(zb0002) {
				z.Strings = (z.Strings)[:zb0002]
			} else {
				z.Strings = make([]ConvertStringVal, zb0002)
			}
			for za0001 := range z.Strings {
				{
					var zb0003 string
					zb0003, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Strings", za0001)
						return
					}
					z.Strings[za0001], err = toConvertStringVal(zb0003)

					if err != nil {
						err = msgp.WrapError(err, "Strings", za0001)
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ConvertStringSlice) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Strings {
		var zb0001 string
		_ = z.Strings[za0001]
		s += msgp.StringPrefixSize + len(zb0001)
	}
	return
}
