// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *AliasedFieldLimitTestData) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "small_aliased_slice":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "SmallAliasedSlice")
				return
			}
			if zb0002 > 3 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.SmallAliasedSlice) >= int(zb0002) {
				z.SmallAliasedSlice = (z.SmallAliasedSlice)[:zb0002]
			} else {
				z.SmallAliasedSlice = make(AliasedSlice, zb0002)
			}
			for za0001 := range z.SmallAliasedSlice {
				z.SmallAliasedSlice[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "SmallAliasedSlice", za0001)
					return
				}
			}
		case "large_aliased_slice":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "LargeAliasedSlice")
				return
			}
			if zb0003 > 50 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.LargeAliasedSlice) >= int(zb0003) {
				z.LargeAliasedSlice = (z.LargeAliasedSlice)[:zb0003]
			} else {
				z.LargeAliasedSlice = make(AliasedSlice, zb0003)
			}
			for za0002 := range z.LargeAliasedSlice {
				z.LargeAliasedSlice[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "LargeAliasedSlice", za0002)
					return
				}
			}
		case "small_aliased_map":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "SmallAliasedMap")
				return
			}
			if zb0004 > 2 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.SmallAliasedMap == nil {
				z.SmallAliasedMap = make(AliasedMap, zb0004)
			} else if len(z.SmallAliasedMap) > 0 {
				clear(z.SmallAliasedMap)
			}
			for zb0004 > 0 {
				zb0004--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "SmallAliasedMap")
					return
				}
				var za0004 bool
				za0004, err = dc.ReadBool()
				if err != nil {
					err = msgp.WrapError(err, "SmallAliasedMap", za0003)
					return
				}
				z.SmallAliasedMap[za0003] = za0004
			}
		case "large_aliased_map":
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "LargeAliasedMap")
				return
			}
			if zb0005 > 25 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.LargeAliasedMap == nil {
				z.LargeAliasedMap = make(AliasedMap, zb0005)
			} else if len(z.LargeAliasedMap) > 0 {
				clear(z.LargeAliasedMap)
			}
			for zb0005 > 0 {
				zb0005--
				var za0005 string
				za0005, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "LargeAliasedMap")
					return
				}
				var za0006 bool
				za0006, err = dc.ReadBool()
				if err != nil {
					err = msgp.WrapError(err, "LargeAliasedMap", za0005)
					return
				}
				z.LargeAliasedMap[za0005] = za0006
			}
		case "int_slice_alias":
			var zb0006 uint32
			zb0006, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "IntSliceAlias")
				return
			}
			if zb0006 > 10 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.IntSliceAlias) >= int(zb0006) {
				z.IntSliceAlias = (z.IntSliceAlias)[:zb0006]
			} else {
				z.IntSliceAlias = make(AliasedIntSlice, zb0006)
			}
			for za0007 := range z.IntSliceAlias {
				z.IntSliceAlias[za0007], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "IntSliceAlias", za0007)
					return
				}
			}
		case "no_limit_alias":
			var zb0007 uint32
			zb0007, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "NoLimitAlias")
				return
			}
			if cap(z.NoLimitAlias) >= int(zb0007) {
				z.NoLimitAlias = (z.NoLimitAlias)[:zb0007]
			} else {
				z.NoLimitAlias = make(AliasedSlice, zb0007)
			}
			for za0008 := range z.NoLimitAlias {
				z.NoLimitAlias[za0008], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "NoLimitAlias", za0008)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *AliasedFieldLimitTestData) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "small_aliased_slice"
	err = en.Append(0x86, 0xb3, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.SmallAliasedSlice)))
	if err != nil {
		err = msgp.WrapError(err, "SmallAliasedSlice")
		return
	}
	for za0001 := range z.SmallAliasedSlice {
		err = en.WriteString(z.SmallAliasedSlice[za0001])
		if err != nil {
			err = msgp.WrapError(err, "SmallAliasedSlice", za0001)
			return
		}
	}
	// write "large_aliased_slice"
	err = en.Append(0xb3, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.LargeAliasedSlice)))
	if err != nil {
		err = msgp.WrapError(err, "LargeAliasedSlice")
		return
	}
	for za0002 := range z.LargeAliasedSlice {
		err = en.WriteString(z.LargeAliasedSlice[za0002])
		if err != nil {
			err = msgp.WrapError(err, "LargeAliasedSlice", za0002)
			return
		}
	}
	// write "small_aliased_map"
	err = en.Append(0xb1, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.SmallAliasedMap)))
	if err != nil {
		err = msgp.WrapError(err, "SmallAliasedMap")
		return
	}
	for za0003, za0004 := range z.SmallAliasedMap {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "SmallAliasedMap")
			return
		}
		err = en.WriteBool(za0004)
		if err != nil {
			err = msgp.WrapError(err, "SmallAliasedMap", za0003)
			return
		}
	}
	// write "large_aliased_map"
	err = en.Append(0xb1, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.LargeAliasedMap)))
	if err != nil {
		err = msgp.WrapError(err, "LargeAliasedMap")
		return
	}
	for za0005, za0006 := range z.LargeAliasedMap {
		err = en.WriteString(za0005)
		if err != nil {
			err = msgp.WrapError(err, "LargeAliasedMap")
			return
		}
		err = en.WriteBool(za0006)
		if err != nil {
			err = msgp.WrapError(err, "LargeAliasedMap", za0005)
			return
		}
	}
	// write "int_slice_alias"
	err = en.Append(0xaf, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.IntSliceAlias)))
	if err != nil {
		err = msgp.WrapError(err, "IntSliceAlias")
		return
	}
	for za0007 := range z.IntSliceAlias {
		err = en.WriteInt(z.IntSliceAlias[za0007])
		if err != nil {
			err = msgp.WrapError(err, "IntSliceAlias", za0007)
			return
		}
	}
	// write "no_limit_alias"
	err = en.Append(0xae, 0x6e, 0x6f, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.NoLimitAlias)))
	if err != nil {
		err = msgp.WrapError(err, "NoLimitAlias")
		return
	}
	for za0008 := range z.NoLimitAlias {
		err = en.WriteString(z.NoLimitAlias[za0008])
		if err != nil {
			err = msgp.WrapError(err, "NoLimitAlias", za0008)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *AliasedFieldLimitTestData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "small_aliased_slice"
	o = append(o, 0x86, 0xb3, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.SmallAliasedSlice)))
	for za0001 := range z.SmallAliasedSlice {
		o = msgp.AppendString(o, z.SmallAliasedSlice[za0001])
	}
	// string "large_aliased_slice"
	o = append(o, 0xb3, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.LargeAliasedSlice)))
	for za0002 := range z.LargeAliasedSlice {
		o = msgp.AppendString(o, z.LargeAliasedSlice[za0002])
	}
	// string "small_aliased_map"
	o = append(o, 0xb1, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.SmallAliasedMap)))
	for za0003, za0004 := range z.SmallAliasedMap {
		o = msgp.AppendString(o, za0003)
		o = msgp.AppendBool(o, za0004)
	}
	// string "large_aliased_map"
	o = append(o, 0xb1, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.LargeAliasedMap)))
	for za0005, za0006 := range z.LargeAliasedMap {
		o = msgp.AppendString(o, za0005)
		o = msgp.AppendBool(o, za0006)
	}
	// string "int_slice_alias"
	o = append(o, 0xaf, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.IntSliceAlias)))
	for za0007 := range z.IntSliceAlias {
		o = msgp.AppendInt(o, z.IntSliceAlias[za0007])
	}
	// string "no_limit_alias"
	o = append(o, 0xae, 0x6e, 0x6f, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.NoLimitAlias)))
	for za0008 := range z.NoLimitAlias {
		o = msgp.AppendString(o, z.NoLimitAlias[za0008])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *AliasedFieldLimitTestData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "small_aliased_slice":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SmallAliasedSlice")
				return
			}
			if zb0002 > 3 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.SmallAliasedSlice) >= int(zb0002) {
				z.SmallAliasedSlice = (z.SmallAliasedSlice)[:zb0002]
			} else {
				z.SmallAliasedSlice = make(AliasedSlice, zb0002)
			}
			for za0001 := range z.SmallAliasedSlice {
				z.SmallAliasedSlice[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SmallAliasedSlice", za0001)
					return
				}
			}
		case "large_aliased_slice":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LargeAliasedSlice")
				return
			}
			if zb0003 > 50 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.LargeAliasedSlice) >= int(zb0003) {
				z.LargeAliasedSlice = (z.LargeAliasedSlice)[:zb0003]
			} else {
				z.LargeAliasedSlice = make(AliasedSlice, zb0003)
			}
			for za0002 := range z.LargeAliasedSlice {
				z.LargeAliasedSlice[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LargeAliasedSlice", za0002)
					return
				}
			}
		case "small_aliased_map":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SmallAliasedMap")
				return
			}
			if zb0004 > 2 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.SmallAliasedMap == nil {
				z.SmallAliasedMap = make(AliasedMap, zb0004)
			} else if len(z.SmallAliasedMap) > 0 {
				clear(z.SmallAliasedMap)
			}
			for zb0004 > 0 {
				var za0004 bool
				zb0004--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SmallAliasedMap")
					return
				}
				za0004, bts, err = msgp.ReadBoolBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SmallAliasedMap", za0003)
					return
				}
				z.SmallAliasedMap[za0003] = za0004
			}
		case "large_aliased_map":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LargeAliasedMap")
				return
			}
			if zb0005 > 25 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.LargeAliasedMap == nil {
				z.LargeAliasedMap = make(AliasedMap, zb0005)
			} else if len(z.LargeAliasedMap) > 0 {
				clear(z.LargeAliasedMap)
			}
			for zb0005 > 0 {
				var za0006 bool
				zb0005--
				var za0005 string
				za0005, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LargeAliasedMap")
					return
				}
				za0006, bts, err = msgp.ReadBoolBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LargeAliasedMap", za0005)
					return
				}
				z.LargeAliasedMap[za0005] = za0006
			}
		case "int_slice_alias":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IntSliceAlias")
				return
			}
			if zb0006 > 10 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.IntSliceAlias) >= int(zb0006) {
				z.IntSliceAlias = (z.IntSliceAlias)[:zb0006]
			} else {
				z.IntSliceAlias = make(AliasedIntSlice, zb0006)
			}
			for za0007 := range z.IntSliceAlias {
				z.IntSliceAlias[za0007], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "IntSliceAlias", za0007)
					return
				}
			}
		case "no_limit_alias":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NoLimitAlias")
				return
			}
			if cap(z.NoLimitAlias) >= int(zb0007) {
				z.NoLimitAlias = (z.NoLimitAlias)[:zb0007]
			} else {
				z.NoLimitAlias = make(AliasedSlice, zb0007)
			}
			for za0008 := range z.NoLimitAlias {
				z.NoLimitAlias[za0008], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "NoLimitAlias", za0008)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *AliasedFieldLimitTestData) Msgsize() (s int) {
	s = 1 + 20 + msgp.ArrayHeaderSize
	for za0001 := range z.SmallAliasedSlice {
		s += msgp.StringPrefixSize + len(z.SmallAliasedSlice[za0001])
	}
	s += 20 + msgp.ArrayHeaderSize
	for za0002 := range z.LargeAliasedSlice {
		s += msgp.StringPrefixSize + len(z.LargeAliasedSlice[za0002])
	}
	s += 18 + msgp.MapHeaderSize
	if z.SmallAliasedMap != nil {
		for za0003, za0004 := range z.SmallAliasedMap {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.BoolSize
		}
	}
	s += 18 + msgp.MapHeaderSize
	if z.LargeAliasedMap != nil {
		for za0005, za0006 := range z.LargeAliasedMap {
			_ = za0006
			s += msgp.StringPrefixSize + len(za0005) + msgp.BoolSize
		}
	}
	s += 16 + msgp.ArrayHeaderSize + (len(z.IntSliceAlias) * (msgp.IntSize)) + 15 + msgp.ArrayHeaderSize
	for za0008 := range z.NoLimitAlias {
		s += msgp.StringPrefixSize + len(z.NoLimitAlias[za0008])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *AliasedIntSlice) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(AliasedIntSlice, zb0002)
	}
	for zb0001 := range *z {
		(*z)[zb0001], err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z AliasedIntSlice) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0003 := range z {
		err = en.WriteInt(z[zb0003])
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z AliasedIntSlice) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0003 := range z {
		o = msgp.AppendInt(o, z[zb0003])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *AliasedIntSlice) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(AliasedIntSlice, zb0002)
	}
	for zb0001 := range *z {
		(*z)[zb0001], bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z AliasedIntSlice) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize + (len(z) * (msgp.IntSize))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *AliasedMap) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(AliasedMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		var zb0002 bool
		zb0002, err = dc.ReadBool()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z AliasedMap) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0004, zb0005 := range z {
		err = en.WriteString(zb0004)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		err = en.WriteBool(zb0005)
		if err != nil {
			err = msgp.WrapError(err, zb0004)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z AliasedMap) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0004, zb0005 := range z {
		o = msgp.AppendString(o, zb0004)
		o = msgp.AppendBool(o, zb0005)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *AliasedMap) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(AliasedMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 bool
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		zb0002, bts, err = msgp.ReadBoolBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z AliasedMap) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0004, zb0005 := range z {
			_ = zb0005
			s += msgp.StringPrefixSize + len(zb0004) + msgp.BoolSize
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *AliasedSlice) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(AliasedSlice, zb0002)
	}
	for zb0001 := range *z {
		(*z)[zb0001], err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z AliasedSlice) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0003 := range z {
		err = en.WriteString(z[zb0003])
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z AliasedSlice) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0003 := range z {
		o = msgp.AppendString(o, z[zb0003])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *AliasedSlice) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(AliasedSlice, zb0002)
	}
	for zb0001 := range *z {
		(*z)[zb0001], bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z AliasedSlice) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0003 := range z {
		s += msgp.StringPrefixSize + len(z[zb0003])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *FieldLimitTestData) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "small_slice":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "SmallSlice")
				return
			}
			if zb0002 > 5 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.SmallSlice) >= int(zb0002) {
				z.SmallSlice = (z.SmallSlice)[:zb0002]
			} else {
				z.SmallSlice = make([]int, zb0002)
			}
			for za0001 := range z.SmallSlice {
				z.SmallSlice[za0001], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "SmallSlice", za0001)
					return
				}
			}
		case "large_slice":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "LargeSlice")
				return
			}
			if zb0003 > 100 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.LargeSlice) >= int(zb0003) {
				z.LargeSlice = (z.LargeSlice)[:zb0003]
			} else {
				z.LargeSlice = make([]string, zb0003)
			}
			for za0002 := range z.LargeSlice {
				z.LargeSlice[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "LargeSlice", za0002)
					return
				}
			}
		case "small_map":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "SmallMap")
				return
			}
			if zb0004 > 3 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.SmallMap == nil {
				z.SmallMap = make(map[string]int, zb0004)
			} else if len(z.SmallMap) > 0 {
				clear(z.SmallMap)
			}
			for zb0004 > 0 {
				zb0004--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "SmallMap")
					return
				}
				var za0004 int
				za0004, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "SmallMap", za0003)
					return
				}
				z.SmallMap[za0003] = za0004
			}
		case "no_limit":
			z.NoLimit, err = dc.ReadBytes(z.NoLimit)
			if err != nil {
				err = msgp.WrapError(err, "NoLimit")
				return
			}
		case "fixed_array":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "FixedArray")
				return
			}
			if zb0005 != uint32(10) {
				err = msgp.ArrayError{Wanted: uint32(10), Got: zb0005}
				return
			}
			for za0005 := range z.FixedArray {
				z.FixedArray[za0005], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "FixedArray", za0005)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *FieldLimitTestData) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "small_slice"
	err = en.Append(0x85, 0xab, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.SmallSlice)))
	if err != nil {
		err = msgp.WrapError(err, "SmallSlice")
		return
	}
	for za0001 := range z.SmallSlice {
		err = en.WriteInt(z.SmallSlice[za0001])
		if err != nil {
			err = msgp.WrapError(err, "SmallSlice", za0001)
			return
		}
	}
	// write "large_slice"
	err = en.Append(0xab, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.LargeSlice)))
	if err != nil {
		err = msgp.WrapError(err, "LargeSlice")
		return
	}
	for za0002 := range z.LargeSlice {
		err = en.WriteString(z.LargeSlice[za0002])
		if err != nil {
			err = msgp.WrapError(err, "LargeSlice", za0002)
			return
		}
	}
	// write "small_map"
	err = en.Append(0xa9, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.SmallMap)))
	if err != nil {
		err = msgp.WrapError(err, "SmallMap")
		return
	}
	for za0003, za0004 := range z.SmallMap {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "SmallMap")
			return
		}
		err = en.WriteInt(za0004)
		if err != nil {
			err = msgp.WrapError(err, "SmallMap", za0003)
			return
		}
	}
	// write "no_limit"
	err = en.Append(0xa8, 0x6e, 0x6f, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.NoLimit)
	if err != nil {
		err = msgp.WrapError(err, "NoLimit")
		return
	}
	// write "fixed_array"
	err = en.Append(0xab, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(10))
	if err != nil {
		err = msgp.WrapError(err, "FixedArray")
		return
	}
	for za0005 := range z.FixedArray {
		err = en.WriteInt(z.FixedArray[za0005])
		if err != nil {
			err = msgp.WrapError(err, "FixedArray", za0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *FieldLimitTestData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "small_slice"
	o = append(o, 0x85, 0xab, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.SmallSlice)))
	for za0001 := range z.SmallSlice {
		o = msgp.AppendInt(o, z.SmallSlice[za0001])
	}
	// string "large_slice"
	o = append(o, 0xab, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.LargeSlice)))
	for za0002 := range z.LargeSlice {
		o = msgp.AppendString(o, z.LargeSlice[za0002])
	}
	// string "small_map"
	o = append(o, 0xa9, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.SmallMap)))
	for za0003, za0004 := range z.SmallMap {
		o = msgp.AppendString(o, za0003)
		o = msgp.AppendInt(o, za0004)
	}
	// string "no_limit"
	o = append(o, 0xa8, 0x6e, 0x6f, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74)
	o = msgp.AppendBytes(o, z.NoLimit)
	// string "fixed_array"
	o = append(o, 0xab, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79)
	o = msgp.AppendArrayHeader(o, uint32(10))
	for za0005 := range z.FixedArray {
		o = msgp.AppendInt(o, z.FixedArray[za0005])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FieldLimitTestData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "small_slice":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SmallSlice")
				return
			}
			if zb0002 > 5 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.SmallSlice) >= int(zb0002) {
				z.SmallSlice = (z.SmallSlice)[:zb0002]
			} else {
				z.SmallSlice = make([]int, zb0002)
			}
			for za0001 := range z.SmallSlice {
				z.SmallSlice[za0001], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SmallSlice", za0001)
					return
				}
			}
		case "large_slice":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LargeSlice")
				return
			}
			if zb0003 > 100 {
				err = msgp.ErrLimitExceeded
				return
			}
			if cap(z.LargeSlice) >= int(zb0003) {
				z.LargeSlice = (z.LargeSlice)[:zb0003]
			} else {
				z.LargeSlice = make([]string, zb0003)
			}
			for za0002 := range z.LargeSlice {
				z.LargeSlice[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LargeSlice", za0002)
					return
				}
			}
		case "small_map":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SmallMap")
				return
			}
			if zb0004 > 3 {
				err = msgp.ErrLimitExceeded
				return
			}
			if z.SmallMap == nil {
				z.SmallMap = make(map[string]int, zb0004)
			} else if len(z.SmallMap) > 0 {
				clear(z.SmallMap)
			}
			for zb0004 > 0 {
				var za0004 int
				zb0004--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SmallMap")
					return
				}
				za0004, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SmallMap", za0003)
					return
				}
				z.SmallMap[za0003] = za0004
			}
		case "no_limit":
			z.NoLimit, bts, err = msgp.ReadBytesBytes(bts, z.NoLimit)
			if err != nil {
				err = msgp.WrapError(err, "NoLimit")
				return
			}
		case "fixed_array":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FixedArray")
				return
			}
			if zb0005 != uint32(10) {
				err = msgp.ArrayError{Wanted: uint32(10), Got: zb0005}
				return
			}
			for za0005 := range z.FixedArray {
				z.FixedArray[za0005], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "FixedArray", za0005)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *FieldLimitTestData) Msgsize() (s int) {
	s = 1 + 12 + msgp.ArrayHeaderSize + (len(z.SmallSlice) * (msgp.IntSize)) + 12 + msgp.ArrayHeaderSize
	for za0002 := range z.LargeSlice {
		s += msgp.StringPrefixSize + len(z.LargeSlice[za0002])
	}
	s += 10 + msgp.MapHeaderSize
	if z.SmallMap != nil {
		for za0003, za0004 := range z.SmallMap {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.IntSize
		}
	}
	s += 9 + msgp.BytesPrefixSize + len(z.NoLimit) + 12 + msgp.ArrayHeaderSize + (10 * (msgp.IntSize))
	return
}
