// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *MyMapKeyStruct) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Map":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Map")
					return
				}
				z.Map = nil
			} else {
				var zb0002 uint32
				zb0002, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Map")
					return
				}
				if z.Map == nil {
					z.Map = make(map[mapKey]int, zb0002)
				} else if len(z.Map) > 0 {
					clear(z.Map)
				}
				for zb0002 > 0 {
					zb0002--
					var za0001 string
					za0001, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Map")
						return
					}
					var za0002 int
					za0002, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Map", za0001)
						return
					}
					var za0001Tmp mapKey
					za0001Tmp, err = stringToMapKey(za0001)
					if err != nil {
						err = msgp.WrapError(err, "shim: stringToMapKey")
						return
					}
					z.Map[za0001Tmp] = za0002
				}
			}
		case "MapS":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "MapS")
					return
				}
				z.MapS = nil
			} else {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "MapS")
					return
				}
				if z.MapS == nil {
					z.MapS = make(map[mapKeyString]int, zb0003)
				} else if len(z.MapS) > 0 {
					clear(z.MapS)
				}
				for zb0003 > 0 {
					zb0003--
					var za0003 string
					za0003, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "MapS")
						return
					}
					var za0004 int
					za0004, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "MapS", za0003)
						return
					}
					z.MapS[mapKeyString(za0003)] = za0004
				}
			}
		case "MapX":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "MapX")
					return
				}
				z.MapX = nil
			} else {
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "MapX")
					return
				}
				if z.MapX == nil {
					z.MapX = make(map[ExternalString]int, zb0004)
				} else if len(z.MapX) > 0 {
					clear(z.MapX)
				}
				for zb0004 > 0 {
					zb0004--
					var za0005 string
					za0005, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "MapX")
						return
					}
					var za0006 int
					za0006, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "MapX", za0005)
						return
					}
					z.MapX[ExternalString(za0005)] = za0006
				}
			}
		case "MapB":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "MapB")
					return
				}
				z.MapB = nil
			} else {
				var zb0005 uint32
				zb0005, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "MapB")
					return
				}
				if z.MapB == nil {
					z.MapB = make(map[mapKeyBytes]int, zb0005)
				} else if len(z.MapB) > 0 {
					clear(z.MapB)
				}
				for zb0005 > 0 {
					zb0005--
					var za0007 string
					za0007, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "MapB")
						return
					}
					var za0008 int
					za0008, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "MapB", za0007)
						return
					}
					var za0007Tmp mapKeyBytes
					za0007Tmp = hexDecode(za0007)
					z.MapB[za0007Tmp] = za0008
				}
			}
		case "Original":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Original")
					return
				}
				z.Original = nil
			} else {
				var zb0006 uint32
				zb0006, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Original")
					return
				}
				if z.Original == nil {
					z.Original = make(map[string]int, zb0006)
				} else if len(z.Original) > 0 {
					clear(z.Original)
				}
				for zb0006 > 0 {
					zb0006--
					var za0009 string
					za0009, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Original")
						return
					}
					var za0010 int
					za0010, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Original", za0009)
						return
					}
					z.Original[za0009] = za0010
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MyMapKeyStruct) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Map"
	err = en.Append(0x85, 0xa3, 0x4d, 0x61, 0x70)
	if err != nil {
		return
	}
	if z.Map == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteMapHeader(uint32(len(z.Map)))
		if err != nil {
			err = msgp.WrapError(err, "Map")
			return
		}
		for za0001, za0002 := range z.Map {
			err = en.WriteString(mapKeyToString(za0001))
			if err != nil {
				err = msgp.WrapError(err, "Map")
				return
			}
			err = en.WriteInt(za0002)
			if err != nil {
				err = msgp.WrapError(err, "Map", za0001)
				return
			}
		}
	}
	// write "MapS"
	err = en.Append(0xa4, 0x4d, 0x61, 0x70, 0x53)
	if err != nil {
		return
	}
	if z.MapS == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteMapHeader(uint32(len(z.MapS)))
		if err != nil {
			err = msgp.WrapError(err, "MapS")
			return
		}
		for za0003, za0004 := range z.MapS {
			err = en.WriteString(string(za0003))
			if err != nil {
				err = msgp.WrapError(err, "MapS")
				return
			}
			err = en.WriteInt(za0004)
			if err != nil {
				err = msgp.WrapError(err, "MapS", za0003)
				return
			}
		}
	}
	// write "MapX"
	err = en.Append(0xa4, 0x4d, 0x61, 0x70, 0x58)
	if err != nil {
		return
	}
	if z.MapX == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteMapHeader(uint32(len(z.MapX)))
		if err != nil {
			err = msgp.WrapError(err, "MapX")
			return
		}
		for za0005, za0006 := range z.MapX {
			err = en.WriteString(string(za0005))
			if err != nil {
				err = msgp.WrapError(err, "MapX")
				return
			}
			err = en.WriteInt(za0006)
			if err != nil {
				err = msgp.WrapError(err, "MapX", za0005)
				return
			}
		}
	}
	// write "MapB"
	err = en.Append(0xa4, 0x4d, 0x61, 0x70, 0x42)
	if err != nil {
		return
	}
	if z.MapB == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteMapHeader(uint32(len(z.MapB)))
		if err != nil {
			err = msgp.WrapError(err, "MapB")
			return
		}
		for za0007, za0008 := range z.MapB {
			err = en.WriteString(hexEncode(za0007))
			if err != nil {
				err = msgp.WrapError(err, "MapB")
				return
			}
			err = en.WriteInt(za0008)
			if err != nil {
				err = msgp.WrapError(err, "MapB", za0007)
				return
			}
		}
	}
	// write "Original"
	err = en.Append(0xa8, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c)
	if err != nil {
		return
	}
	if z.Original == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteMapHeader(uint32(len(z.Original)))
		if err != nil {
			err = msgp.WrapError(err, "Original")
			return
		}
		for za0009, za0010 := range z.Original {
			err = en.WriteString(za0009)
			if err != nil {
				err = msgp.WrapError(err, "Original")
				return
			}
			err = en.WriteInt(za0010)
			if err != nil {
				err = msgp.WrapError(err, "Original", za0009)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MyMapKeyStruct) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Map"
	o = append(o, 0x85, 0xa3, 0x4d, 0x61, 0x70)
	if z.Map == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendMapHeader(o, uint32(len(z.Map)))
		for za0001, za0002 := range z.Map {
			o = msgp.AppendString(o, mapKeyToString(za0001))
			o = msgp.AppendInt(o, za0002)
		}
	}
	// string "MapS"
	o = append(o, 0xa4, 0x4d, 0x61, 0x70, 0x53)
	if z.MapS == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendMapHeader(o, uint32(len(z.MapS)))
		for za0003, za0004 := range z.MapS {
			o = msgp.AppendString(o, string(za0003))
			o = msgp.AppendInt(o, za0004)
		}
	}
	// string "MapX"
	o = append(o, 0xa4, 0x4d, 0x61, 0x70, 0x58)
	if z.MapX == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendMapHeader(o, uint32(len(z.MapX)))
		for za0005, za0006 := range z.MapX {
			o = msgp.AppendString(o, string(za0005))
			o = msgp.AppendInt(o, za0006)
		}
	}
	// string "MapB"
	o = append(o, 0xa4, 0x4d, 0x61, 0x70, 0x42)
	if z.MapB == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendMapHeader(o, uint32(len(z.MapB)))
		for za0007, za0008 := range z.MapB {
			o = msgp.AppendString(o, hexEncode(za0007))
			o = msgp.AppendInt(o, za0008)
		}
	}
	// string "Original"
	o = append(o, 0xa8, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c)
	if z.Original == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendMapHeader(o, uint32(len(z.Original)))
		for za0009, za0010 := range z.Original {
			o = msgp.AppendString(o, za0009)
			o = msgp.AppendInt(o, za0010)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MyMapKeyStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Map":
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.Map = nil
			} else {
				var zb0002 uint32
				zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Map")
					return
				}
				if z.Map == nil {
					z.Map = make(map[mapKey]int, zb0002)
				} else if len(z.Map) > 0 {
					clear(z.Map)
				}
				for zb0002 > 0 {
					var za0002 int
					zb0002--
					var za0001 string
					za0001, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Map")
						return
					}
					za0002, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Map", za0001)
						return
					}
					var za0001Tmp mapKey
					za0001Tmp, err = stringToMapKey(za0001)
					if err != nil {
						err = msgp.WrapError(err, "shim: stringToMapKey")
						return
					}
					z.Map[za0001Tmp] = za0002
				}
			}
		case "MapS":
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.MapS = nil
			} else {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MapS")
					return
				}
				if z.MapS == nil {
					z.MapS = make(map[mapKeyString]int, zb0003)
				} else if len(z.MapS) > 0 {
					clear(z.MapS)
				}
				for zb0003 > 0 {
					var za0004 int
					zb0003--
					var za0003 string
					za0003, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "MapS")
						return
					}
					za0004, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "MapS", za0003)
						return
					}
					z.MapS[mapKeyString(za0003)] = za0004
				}
			}
		case "MapX":
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.MapX = nil
			} else {
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MapX")
					return
				}
				if z.MapX == nil {
					z.MapX = make(map[ExternalString]int, zb0004)
				} else if len(z.MapX) > 0 {
					clear(z.MapX)
				}
				for zb0004 > 0 {
					var za0006 int
					zb0004--
					var za0005 string
					za0005, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "MapX")
						return
					}
					za0006, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "MapX", za0005)
						return
					}
					z.MapX[ExternalString(za0005)] = za0006
				}
			}
		case "MapB":
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.MapB = nil
			} else {
				var zb0005 uint32
				zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MapB")
					return
				}
				if z.MapB == nil {
					z.MapB = make(map[mapKeyBytes]int, zb0005)
				} else if len(z.MapB) > 0 {
					clear(z.MapB)
				}
				for zb0005 > 0 {
					var za0008 int
					zb0005--
					var za0007 string
					za0007, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "MapB")
						return
					}
					za0008, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "MapB", za0007)
						return
					}
					var za0007Tmp mapKeyBytes
					za0007Tmp = hexDecode(za0007)
					z.MapB[za0007Tmp] = za0008
				}
			}
		case "Original":
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.Original = nil
			} else {
				var zb0006 uint32
				zb0006, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Original")
					return
				}
				if z.Original == nil {
					z.Original = make(map[string]int, zb0006)
				} else if len(z.Original) > 0 {
					clear(z.Original)
				}
				for zb0006 > 0 {
					var za0010 int
					zb0006--
					var za0009 string
					za0009, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Original")
						return
					}
					za0010, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Original", za0009)
						return
					}
					z.Original[za0009] = za0010
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MyMapKeyStruct) Msgsize() (s int) {
	s = 1 + 4 + msgp.MapHeaderSize
	if z.Map != nil {
		for za0001, za0002 := range z.Map {
			_ = za0002
			s += msgp.StringPrefixSize + len(mapKeyToString(za0001)) + msgp.IntSize
		}
	}
	s += 5 + msgp.MapHeaderSize
	if z.MapS != nil {
		for za0003, za0004 := range z.MapS {
			_ = za0004
			s += msgp.StringPrefixSize + len(mapKeyString(za0003)) + msgp.IntSize
		}
	}
	s += 5 + msgp.MapHeaderSize
	if z.MapX != nil {
		for za0005, za0006 := range z.MapX {
			_ = za0006
			s += msgp.StringPrefixSize + len(string(za0005)) + msgp.IntSize
		}
	}
	s += 5 + msgp.MapHeaderSize
	if z.MapB != nil {
		for za0007, za0008 := range z.MapB {
			_ = za0008
			s += msgp.StringPrefixSize + len(hexEncode(za0007)) + msgp.IntSize
		}
	}
	s += 9 + msgp.MapHeaderSize
	if z.Original != nil {
		for za0009, za0010 := range z.Original {
			_ = za0010
			s += msgp.StringPrefixSize + len(za0009) + msgp.IntSize
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *mapKey) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z), err = stringToMapKey(zb0001)
	}
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z mapKey) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(mapKeyToString(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z mapKey) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, mapKeyToString(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *mapKey) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z), err = stringToMapKey(zb0001)

		if err != nil {
			err = msgp.WrapError(err)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z mapKey) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(mapKeyToString(z))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *mapKeyBytes) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = hexDecode(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z mapKeyBytes) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(hexEncode(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z mapKeyBytes) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, hexEncode(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *mapKeyBytes) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = hexDecode(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z mapKeyBytes) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(hexEncode(z))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *mapKeyString) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = mapKeyString(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z mapKeyString) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(string(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z mapKeyString) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, string(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *mapKeyString) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = mapKeyString(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z mapKeyString) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(string(z))
	return
}
