// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *NoDupBinKeyArray) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupBinKeyArray, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 [2]byte
		err = dc.ReadExactBytes((zb0001)[:])
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		if _, zb0005 := (*z)[zb0001]; zb0005 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		var zb0002 int
		zb0002, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupBinKeyArray) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0006, zb0007 := range z {
		err = en.WriteBytes((zb0006)[:])
		if err != nil {
			err = msgp.WrapError(err, zb0006)
			return
		}
		err = en.WriteInt(zb0007)
		if err != nil {
			err = msgp.WrapError(err, zb0006)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupBinKeyArray) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0006, zb0007 := range z {
		o = msgp.AppendBytes(o, (zb0006)[:])
		o = msgp.AppendInt(o, zb0007)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupBinKeyArray) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupBinKeyArray, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 int
		zb0003--
		var zb0001 [2]byte
		bts, err = msgp.ReadExactBytes(bts, (zb0001)[:])
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		if _, zb0005 := (*z)[zb0001]; zb0005 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		zb0002, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupBinKeyArray) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0006, zb0007 := range z {
			_ = zb0007
			s += msgp.StringPrefixSize + len(zb0006) + msgp.IntSize
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupBinKeyInt) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupBinKeyInt, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 int
		zb0001, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		var zb0002 string
		zb0002, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupBinKeyInt) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0005, zb0006 := range z {
		err = en.WriteInt(zb0005)
		if err != nil {
			err = msgp.WrapError(err, zb0005)
			return
		}
		err = en.WriteString(zb0006)
		if err != nil {
			err = msgp.WrapError(err, zb0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupBinKeyInt) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0005, zb0006 := range z {
		o = msgp.AppendInt(o, zb0005)
		o = msgp.AppendString(o, zb0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupBinKeyInt) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupBinKeyInt, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 string
		zb0003--
		var zb0001 int
		zb0001, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		zb0002, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupBinKeyInt) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0005, zb0006 := range z {
			_ = zb0006
			_ = zb0005
			s += msgp.IntSize + msgp.StringPrefixSize + len(zb0006)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupBinKeyStruct) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Name")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "int_map":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "IntMap")
				return
			}
			zb0001Dup[0] |= 1 << 1
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "IntMap")
				return
			}
			if z.IntMap == nil {
				z.IntMap = make(map[int]string, zb0002)
			} else if len(z.IntMap) > 0 {
				clear(z.IntMap)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 int
				za0001, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "IntMap", za0001)
					return
				}
				if _, zb0003 := z.IntMap[za0001]; zb0003 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "IntMap", za0001)
					return
				}
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "IntMap", za0001)
					return
				}
				z.IntMap[za0001] = za0002
			}
		case "str_map":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "StrMap")
				return
			}
			zb0001Dup[0] |= 1 << 2
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "StrMap")
				return
			}
			if z.StrMap == nil {
				z.StrMap = make(map[string]int, zb0004)
			} else if len(z.StrMap) > 0 {
				clear(z.StrMap)
			}
			for zb0004 > 0 {
				zb0004--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "StrMap")
					return
				}
				if _, zb0005 := z.StrMap[za0003]; zb0005 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "StrMap", za0003)
					return
				}
				var za0004 int
				za0004, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "StrMap", za0003)
					return
				}
				z.StrMap[za0003] = za0004
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NoDupBinKeyStruct) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "name"
	err = en.Append(0x83, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "int_map"
	err = en.Append(0xa7, 0x69, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.IntMap)))
	if err != nil {
		err = msgp.WrapError(err, "IntMap")
		return
	}
	for za0001, za0002 := range z.IntMap {
		err = en.WriteInt(za0001)
		if err != nil {
			err = msgp.WrapError(err, "IntMap", za0001)
			return
		}
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "IntMap", za0001)
			return
		}
	}
	// write "str_map"
	err = en.Append(0xa7, 0x73, 0x74, 0x72, 0x5f, 0x6d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.StrMap)))
	if err != nil {
		err = msgp.WrapError(err, "StrMap")
		return
	}
	for za0003, za0004 := range z.StrMap {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "StrMap")
			return
		}
		err = en.WriteInt(za0004)
		if err != nil {
			err = msgp.WrapError(err, "StrMap", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NoDupBinKeyStruct) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "name"
	o = append(o, 0x83, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "int_map"
	o = append(o, 0xa7, 0x69, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.IntMap)))
	for za0001, za0002 := range z.IntMap {
		o = msgp.AppendInt(o, za0001)
		o = msgp.AppendString(o, za0002)
	}
	// string "str_map"
	o = append(o, 0xa7, 0x73, 0x74, 0x72, 0x5f, 0x6d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.StrMap)))
	for za0003, za0004 := range z.StrMap {
		o = msgp.AppendString(o, za0003)
		o = msgp.AppendInt(o, za0004)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupBinKeyStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Name")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "int_map":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "IntMap")
				return
			}
			zb0001Dup[0] |= 1 << 1
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IntMap")
				return
			}
			if z.IntMap == nil {
				z.IntMap = make(map[int]string, zb0002)
			} else if len(z.IntMap) > 0 {
				clear(z.IntMap)
			}
			for zb0002 > 0 {
				var za0002 string
				zb0002--
				var za0001 int
				za0001, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "IntMap", za0001)
					return
				}
				if _, zb0003 := z.IntMap[za0001]; zb0003 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "IntMap", za0001)
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "IntMap", za0001)
					return
				}
				z.IntMap[za0001] = za0002
			}
		case "str_map":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "StrMap")
				return
			}
			zb0001Dup[0] |= 1 << 2
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StrMap")
				return
			}
			if z.StrMap == nil {
				z.StrMap = make(map[string]int, zb0004)
			} else if len(z.StrMap) > 0 {
				clear(z.StrMap)
			}
			for zb0004 > 0 {
				var za0004 int
				zb0004--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StrMap")
					return
				}
				if _, zb0005 := z.StrMap[za0003]; zb0005 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "StrMap", za0003)
					return
				}
				za0004, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StrMap", za0003)
					return
				}
				z.StrMap[za0003] = za0004
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NoDupBinKeyStruct) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 8 + msgp.MapHeaderSize
	if z.IntMap != nil {
		for za0001, za0002 := range z.IntMap {
			_ = za0002
			_ = za0001
			s += msgp.IntSize + msgp.StringPrefixSize + len(za0002)
		}
	}
	s += 8 + msgp.MapHeaderSize
	if z.StrMap != nil {
		for za0003, za0004 := range z.StrMap {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.IntSize
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupBinKeyUint32) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupBinKeyUint32, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 uint32
		zb0001, err = dc.ReadUint32()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		var zb0002 int
		zb0002, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupBinKeyUint32) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0005, zb0006 := range z {
		err = en.WriteUint32(zb0005)
		if err != nil {
			err = msgp.WrapError(err, zb0005)
			return
		}
		err = en.WriteInt(zb0006)
		if err != nil {
			err = msgp.WrapError(err, zb0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupBinKeyUint32) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0005, zb0006 := range z {
		o = msgp.AppendUint32(o, zb0005)
		o = msgp.AppendInt(o, zb0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupBinKeyUint32) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupBinKeyUint32, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 int
		zb0003--
		var zb0001 uint32
		zb0001, bts, err = msgp.ReadUint32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		zb0002, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupBinKeyUint32) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0005, zb0006 := range z {
			_ = zb0006
			_ = zb0005
			s += msgp.Uint32Size + msgp.IntSize
		}
	}
	return
}
