// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *NoDup17Fields) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [3]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "a01":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A01")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.A01, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A01")
				return
			}
		case "a02":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A02")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.A02, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A02")
				return
			}
		case "a03":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A03")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.A03, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A03")
				return
			}
		case "a04":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A04")
				return
			}
			zb0001Dup[0] |= 1 << 3
			z.A04, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A04")
				return
			}
		case "a05":
			if zb0001Dup[0]&(1<<4) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A05")
				return
			}
			zb0001Dup[0] |= 1 << 4
			z.A05, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A05")
				return
			}
		case "a06":
			if zb0001Dup[0]&(1<<5) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A06")
				return
			}
			zb0001Dup[0] |= 1 << 5
			z.A06, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A06")
				return
			}
		case "a07":
			if zb0001Dup[0]&(1<<6) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A07")
				return
			}
			zb0001Dup[0] |= 1 << 6
			z.A07, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A07")
				return
			}
		case "a08":
			if zb0001Dup[0]&(1<<7) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A08")
				return
			}
			zb0001Dup[0] |= 1 << 7
			z.A08, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A08")
				return
			}
		case "a09":
			if zb0001Dup[1]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A09")
				return
			}
			zb0001Dup[1] |= 1 << 0
			z.A09, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A09")
				return
			}
		case "a10":
			if zb0001Dup[1]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A10")
				return
			}
			zb0001Dup[1] |= 1 << 1
			z.A10, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A10")
				return
			}
		case "a11":
			if zb0001Dup[1]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A11")
				return
			}
			zb0001Dup[1] |= 1 << 2
			z.A11, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A11")
				return
			}
		case "a12":
			if zb0001Dup[1]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A12")
				return
			}
			zb0001Dup[1] |= 1 << 3
			z.A12, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A12")
				return
			}
		case "a13":
			if zb0001Dup[1]&(1<<4) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A13")
				return
			}
			zb0001Dup[1] |= 1 << 4
			z.A13, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A13")
				return
			}
		case "a14":
			if zb0001Dup[1]&(1<<5) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A14")
				return
			}
			zb0001Dup[1] |= 1 << 5
			z.A14, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A14")
				return
			}
		case "a15":
			if zb0001Dup[1]&(1<<6) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A15")
				return
			}
			zb0001Dup[1] |= 1 << 6
			z.A15, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A15")
				return
			}
		case "a16":
			if zb0001Dup[1]&(1<<7) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A16")
				return
			}
			zb0001Dup[1] |= 1 << 7
			z.A16, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A16")
				return
			}
		case "a17":
			if zb0001Dup[2]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A17")
				return
			}
			zb0001Dup[2] |= 1 << 0
			z.A17, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "A17")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NoDup17Fields) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 17
	// write "a01"
	err = en.Append(0xde, 0x0, 0x11, 0xa3, 0x61, 0x30, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A01)
	if err != nil {
		err = msgp.WrapError(err, "A01")
		return
	}
	// write "a02"
	err = en.Append(0xa3, 0x61, 0x30, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A02)
	if err != nil {
		err = msgp.WrapError(err, "A02")
		return
	}
	// write "a03"
	err = en.Append(0xa3, 0x61, 0x30, 0x33)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A03)
	if err != nil {
		err = msgp.WrapError(err, "A03")
		return
	}
	// write "a04"
	err = en.Append(0xa3, 0x61, 0x30, 0x34)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A04)
	if err != nil {
		err = msgp.WrapError(err, "A04")
		return
	}
	// write "a05"
	err = en.Append(0xa3, 0x61, 0x30, 0x35)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A05)
	if err != nil {
		err = msgp.WrapError(err, "A05")
		return
	}
	// write "a06"
	err = en.Append(0xa3, 0x61, 0x30, 0x36)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A06)
	if err != nil {
		err = msgp.WrapError(err, "A06")
		return
	}
	// write "a07"
	err = en.Append(0xa3, 0x61, 0x30, 0x37)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A07)
	if err != nil {
		err = msgp.WrapError(err, "A07")
		return
	}
	// write "a08"
	err = en.Append(0xa3, 0x61, 0x30, 0x38)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A08)
	if err != nil {
		err = msgp.WrapError(err, "A08")
		return
	}
	// write "a09"
	err = en.Append(0xa3, 0x61, 0x30, 0x39)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A09)
	if err != nil {
		err = msgp.WrapError(err, "A09")
		return
	}
	// write "a10"
	err = en.Append(0xa3, 0x61, 0x31, 0x30)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A10)
	if err != nil {
		err = msgp.WrapError(err, "A10")
		return
	}
	// write "a11"
	err = en.Append(0xa3, 0x61, 0x31, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A11)
	if err != nil {
		err = msgp.WrapError(err, "A11")
		return
	}
	// write "a12"
	err = en.Append(0xa3, 0x61, 0x31, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A12)
	if err != nil {
		err = msgp.WrapError(err, "A12")
		return
	}
	// write "a13"
	err = en.Append(0xa3, 0x61, 0x31, 0x33)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A13)
	if err != nil {
		err = msgp.WrapError(err, "A13")
		return
	}
	// write "a14"
	err = en.Append(0xa3, 0x61, 0x31, 0x34)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A14)
	if err != nil {
		err = msgp.WrapError(err, "A14")
		return
	}
	// write "a15"
	err = en.Append(0xa3, 0x61, 0x31, 0x35)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A15)
	if err != nil {
		err = msgp.WrapError(err, "A15")
		return
	}
	// write "a16"
	err = en.Append(0xa3, 0x61, 0x31, 0x36)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A16)
	if err != nil {
		err = msgp.WrapError(err, "A16")
		return
	}
	// write "a17"
	err = en.Append(0xa3, 0x61, 0x31, 0x37)
	if err != nil {
		return
	}
	err = en.WriteInt(z.A17)
	if err != nil {
		err = msgp.WrapError(err, "A17")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NoDup17Fields) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 17
	// string "a01"
	o = append(o, 0xde, 0x0, 0x11, 0xa3, 0x61, 0x30, 0x31)
	o = msgp.AppendInt(o, z.A01)
	// string "a02"
	o = append(o, 0xa3, 0x61, 0x30, 0x32)
	o = msgp.AppendInt(o, z.A02)
	// string "a03"
	o = append(o, 0xa3, 0x61, 0x30, 0x33)
	o = msgp.AppendInt(o, z.A03)
	// string "a04"
	o = append(o, 0xa3, 0x61, 0x30, 0x34)
	o = msgp.AppendInt(o, z.A04)
	// string "a05"
	o = append(o, 0xa3, 0x61, 0x30, 0x35)
	o = msgp.AppendInt(o, z.A05)
	// string "a06"
	o = append(o, 0xa3, 0x61, 0x30, 0x36)
	o = msgp.AppendInt(o, z.A06)
	// string "a07"
	o = append(o, 0xa3, 0x61, 0x30, 0x37)
	o = msgp.AppendInt(o, z.A07)
	// string "a08"
	o = append(o, 0xa3, 0x61, 0x30, 0x38)
	o = msgp.AppendInt(o, z.A08)
	// string "a09"
	o = append(o, 0xa3, 0x61, 0x30, 0x39)
	o = msgp.AppendInt(o, z.A09)
	// string "a10"
	o = append(o, 0xa3, 0x61, 0x31, 0x30)
	o = msgp.AppendInt(o, z.A10)
	// string "a11"
	o = append(o, 0xa3, 0x61, 0x31, 0x31)
	o = msgp.AppendInt(o, z.A11)
	// string "a12"
	o = append(o, 0xa3, 0x61, 0x31, 0x32)
	o = msgp.AppendInt(o, z.A12)
	// string "a13"
	o = append(o, 0xa3, 0x61, 0x31, 0x33)
	o = msgp.AppendInt(o, z.A13)
	// string "a14"
	o = append(o, 0xa3, 0x61, 0x31, 0x34)
	o = msgp.AppendInt(o, z.A14)
	// string "a15"
	o = append(o, 0xa3, 0x61, 0x31, 0x35)
	o = msgp.AppendInt(o, z.A15)
	// string "a16"
	o = append(o, 0xa3, 0x61, 0x31, 0x36)
	o = msgp.AppendInt(o, z.A16)
	// string "a17"
	o = append(o, 0xa3, 0x61, 0x31, 0x37)
	o = msgp.AppendInt(o, z.A17)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDup17Fields) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [3]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "a01":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A01")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.A01, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A01")
				return
			}
		case "a02":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A02")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.A02, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A02")
				return
			}
		case "a03":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A03")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.A03, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A03")
				return
			}
		case "a04":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A04")
				return
			}
			zb0001Dup[0] |= 1 << 3
			z.A04, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A04")
				return
			}
		case "a05":
			if zb0001Dup[0]&(1<<4) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A05")
				return
			}
			zb0001Dup[0] |= 1 << 4
			z.A05, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A05")
				return
			}
		case "a06":
			if zb0001Dup[0]&(1<<5) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A06")
				return
			}
			zb0001Dup[0] |= 1 << 5
			z.A06, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A06")
				return
			}
		case "a07":
			if zb0001Dup[0]&(1<<6) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A07")
				return
			}
			zb0001Dup[0] |= 1 << 6
			z.A07, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A07")
				return
			}
		case "a08":
			if zb0001Dup[0]&(1<<7) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A08")
				return
			}
			zb0001Dup[0] |= 1 << 7
			z.A08, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A08")
				return
			}
		case "a09":
			if zb0001Dup[1]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A09")
				return
			}
			zb0001Dup[1] |= 1 << 0
			z.A09, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A09")
				return
			}
		case "a10":
			if zb0001Dup[1]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A10")
				return
			}
			zb0001Dup[1] |= 1 << 1
			z.A10, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A10")
				return
			}
		case "a11":
			if zb0001Dup[1]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A11")
				return
			}
			zb0001Dup[1] |= 1 << 2
			z.A11, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A11")
				return
			}
		case "a12":
			if zb0001Dup[1]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A12")
				return
			}
			zb0001Dup[1] |= 1 << 3
			z.A12, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A12")
				return
			}
		case "a13":
			if zb0001Dup[1]&(1<<4) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A13")
				return
			}
			zb0001Dup[1] |= 1 << 4
			z.A13, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A13")
				return
			}
		case "a14":
			if zb0001Dup[1]&(1<<5) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A14")
				return
			}
			zb0001Dup[1] |= 1 << 5
			z.A14, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A14")
				return
			}
		case "a15":
			if zb0001Dup[1]&(1<<6) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A15")
				return
			}
			zb0001Dup[1] |= 1 << 6
			z.A15, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A15")
				return
			}
		case "a16":
			if zb0001Dup[1]&(1<<7) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A16")
				return
			}
			zb0001Dup[1] |= 1 << 7
			z.A16, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A16")
				return
			}
		case "a17":
			if zb0001Dup[2]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "A17")
				return
			}
			zb0001Dup[2] |= 1 << 0
			z.A17, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "A17")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NoDup17Fields) Msgsize() (s int) {
	s = 3 + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize + 4 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupAllownil) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Name")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "vals":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Vals")
				return
			}
			zb0001Dup[0] |= 1 << 1
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Vals")
					return
				}
				z.Vals = nil
			} else {
				z.Vals, err = dc.ReadBytes(z.Vals)
				if err != nil {
					err = msgp.WrapError(err, "Vals")
					return
				}
				if z.Vals == nil {
					z.Vals = make([]byte, 0)
				}
			}
		case "items":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Items")
				return
			}
			zb0001Dup[0] |= 1 << 2
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Items")
					return
				}
				z.Items = nil
			} else {
				var zb0002 uint32
				zb0002, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "Items")
					return
				}
				if z.Items != nil && cap(z.Items) >= int(zb0002) {
					z.Items = (z.Items)[:zb0002]
				} else {
					z.Items = make([]int, zb0002)
				}
				for za0001 := range z.Items {
					z.Items[za0001], err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Items", za0001)
						return
					}
				}
			}
		case "mapping":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Mapping")
				return
			}
			zb0001Dup[0] |= 1 << 3
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Mapping")
					return
				}
				z.Mapping = nil
			} else {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Mapping")
					return
				}
				if z.Mapping == nil {
					z.Mapping = make(map[string]string, zb0003)
				} else if len(z.Mapping) > 0 {
					clear(z.Mapping)
				}
				for zb0003 > 0 {
					zb0003--
					var za0002 string
					za0002, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Mapping")
						return
					}
					if _, zb0004 := z.Mapping[za0002]; zb0004 {
						err = msgp.WrapError(msgp.ErrDuplicateEntry, "Mapping", za0002)
						return
					}
					var za0003 string
					za0003, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Mapping", za0002)
						return
					}
					z.Mapping[za0002] = za0003
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NoDupAllownil) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "name"
	err = en.Append(0x84, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "vals"
	err = en.Append(0xa4, 0x76, 0x61, 0x6c, 0x73)
	if err != nil {
		return
	}
	if z.Vals == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBytes(z.Vals)
		if err != nil {
			err = msgp.WrapError(err, "Vals")
			return
		}
	}
	// write "items"
	err = en.Append(0xa5, 0x69, 0x74, 0x65, 0x6d, 0x73)
	if err != nil {
		return
	}
	if z.Items == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteArrayHeader(uint32(len(z.Items)))
		if err != nil {
			err = msgp.WrapError(err, "Items")
			return
		}
		for za0001 := range z.Items {
			err = en.WriteInt(z.Items[za0001])
			if err != nil {
				err = msgp.WrapError(err, "Items", za0001)
				return
			}
		}
	}
	// write "mapping"
	err = en.Append(0xa7, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	if z.Mapping == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteMapHeader(uint32(len(z.Mapping)))
		if err != nil {
			err = msgp.WrapError(err, "Mapping")
			return
		}
		for za0002, za0003 := range z.Mapping {
			err = en.WriteString(za0002)
			if err != nil {
				err = msgp.WrapError(err, "Mapping")
				return
			}
			err = en.WriteString(za0003)
			if err != nil {
				err = msgp.WrapError(err, "Mapping", za0002)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NoDupAllownil) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "name"
	o = append(o, 0x84, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "vals"
	o = append(o, 0xa4, 0x76, 0x61, 0x6c, 0x73)
	if z.Vals == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBytes(o, z.Vals)
	}
	// string "items"
	o = append(o, 0xa5, 0x69, 0x74, 0x65, 0x6d, 0x73)
	if z.Items == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendArrayHeader(o, uint32(len(z.Items)))
		for za0001 := range z.Items {
			o = msgp.AppendInt(o, z.Items[za0001])
		}
	}
	// string "mapping"
	o = append(o, 0xa7, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67)
	if z.Mapping == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendMapHeader(o, uint32(len(z.Mapping)))
		for za0002, za0003 := range z.Mapping {
			o = msgp.AppendString(o, za0002)
			o = msgp.AppendString(o, za0003)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupAllownil) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Name")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "vals":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Vals")
				return
			}
			zb0001Dup[0] |= 1 << 1
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.Vals = nil
			} else {
				z.Vals, bts, err = msgp.ReadBytesBytes(bts, z.Vals)
				if err != nil {
					err = msgp.WrapError(err, "Vals")
					return
				}
				if z.Vals == nil {
					z.Vals = make([]byte, 0)
				}
			}
		case "items":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Items")
				return
			}
			zb0001Dup[0] |= 1 << 2
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.Items = nil
			} else {
				var zb0002 uint32
				zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Items")
					return
				}
				if z.Items != nil && cap(z.Items) >= int(zb0002) {
					z.Items = (z.Items)[:zb0002]
				} else {
					z.Items = make([]int, zb0002)
				}
				for za0001 := range z.Items {
					z.Items[za0001], bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Items", za0001)
						return
					}
				}
			}
		case "mapping":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Mapping")
				return
			}
			zb0001Dup[0] |= 1 << 3
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.Mapping = nil
			} else {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Mapping")
					return
				}
				if z.Mapping == nil {
					z.Mapping = make(map[string]string, zb0003)
				} else if len(z.Mapping) > 0 {
					clear(z.Mapping)
				}
				for zb0003 > 0 {
					var za0003 string
					zb0003--
					var za0002 string
					za0002, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Mapping")
						return
					}
					if _, zb0004 := z.Mapping[za0002]; zb0004 {
						err = msgp.WrapError(msgp.ErrDuplicateEntry, "Mapping", za0002)
						return
					}
					za0003, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Mapping", za0002)
						return
					}
					z.Mapping[za0002] = za0003
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NoDupAllownil) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 5 + msgp.BytesPrefixSize + len(z.Vals) + 6 + msgp.ArrayHeaderSize + (len(z.Items) * (msgp.IntSize)) + 8 + msgp.MapHeaderSize
	if z.Mapping != nil {
		for za0002, za0003 := range z.Mapping {
			_ = za0003
			s += msgp.StringPrefixSize + len(za0002) + msgp.StringPrefixSize + len(za0003)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupInner) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "x":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "X")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.X, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "y":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Y")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Y, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupInner) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "x"
	err = en.Append(0x82, 0xa1, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt(z.X)
	if err != nil {
		err = msgp.WrapError(err, "X")
		return
	}
	// write "y"
	err = en.Append(0xa1, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Y)
	if err != nil {
		err = msgp.WrapError(err, "Y")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupInner) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "x"
	o = append(o, 0x82, 0xa1, 0x78)
	o = msgp.AppendInt(o, z.X)
	// string "y"
	o = append(o, 0xa1, 0x79)
	o = msgp.AppendString(o, z.Y)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupInner) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "x":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "X")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.X, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "X")
				return
			}
		case "y":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Y")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Y, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Y")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupInner) Msgsize() (s int) {
	s = 1 + 2 + msgp.IntSize + 2 + msgp.StringPrefixSize + len(z.Y)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupManyFields) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [2]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "f01":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F01")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.F01, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F01")
				return
			}
		case "f02":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F02")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.F02, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F02")
				return
			}
		case "f03":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F03")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.F03, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F03")
				return
			}
		case "f04":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F04")
				return
			}
			zb0001Dup[0] |= 1 << 3
			z.F04, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F04")
				return
			}
		case "f05":
			if zb0001Dup[0]&(1<<4) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F05")
				return
			}
			zb0001Dup[0] |= 1 << 4
			z.F05, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F05")
				return
			}
		case "f06":
			if zb0001Dup[0]&(1<<5) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F06")
				return
			}
			zb0001Dup[0] |= 1 << 5
			z.F06, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F06")
				return
			}
		case "f07":
			if zb0001Dup[0]&(1<<6) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F07")
				return
			}
			zb0001Dup[0] |= 1 << 6
			z.F07, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F07")
				return
			}
		case "f08":
			if zb0001Dup[0]&(1<<7) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F08")
				return
			}
			zb0001Dup[0] |= 1 << 7
			z.F08, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F08")
				return
			}
		case "f09":
			if zb0001Dup[1]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F09")
				return
			}
			zb0001Dup[1] |= 1 << 0
			z.F09, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F09")
				return
			}
		case "f10":
			if zb0001Dup[1]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F10")
				return
			}
			zb0001Dup[1] |= 1 << 1
			z.F10, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "F10")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NoDupManyFields) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 10
	// write "f01"
	err = en.Append(0x8a, 0xa3, 0x66, 0x30, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.F01)
	if err != nil {
		err = msgp.WrapError(err, "F01")
		return
	}
	// write "f02"
	err = en.Append(0xa3, 0x66, 0x30, 0x32)
	if err != nil {
		return
	}
	err = en.WriteString(z.F02)
	if err != nil {
		err = msgp.WrapError(err, "F02")
		return
	}
	// write "f03"
	err = en.Append(0xa3, 0x66, 0x30, 0x33)
	if err != nil {
		return
	}
	err = en.WriteString(z.F03)
	if err != nil {
		err = msgp.WrapError(err, "F03")
		return
	}
	// write "f04"
	err = en.Append(0xa3, 0x66, 0x30, 0x34)
	if err != nil {
		return
	}
	err = en.WriteString(z.F04)
	if err != nil {
		err = msgp.WrapError(err, "F04")
		return
	}
	// write "f05"
	err = en.Append(0xa3, 0x66, 0x30, 0x35)
	if err != nil {
		return
	}
	err = en.WriteString(z.F05)
	if err != nil {
		err = msgp.WrapError(err, "F05")
		return
	}
	// write "f06"
	err = en.Append(0xa3, 0x66, 0x30, 0x36)
	if err != nil {
		return
	}
	err = en.WriteString(z.F06)
	if err != nil {
		err = msgp.WrapError(err, "F06")
		return
	}
	// write "f07"
	err = en.Append(0xa3, 0x66, 0x30, 0x37)
	if err != nil {
		return
	}
	err = en.WriteString(z.F07)
	if err != nil {
		err = msgp.WrapError(err, "F07")
		return
	}
	// write "f08"
	err = en.Append(0xa3, 0x66, 0x30, 0x38)
	if err != nil {
		return
	}
	err = en.WriteString(z.F08)
	if err != nil {
		err = msgp.WrapError(err, "F08")
		return
	}
	// write "f09"
	err = en.Append(0xa3, 0x66, 0x30, 0x39)
	if err != nil {
		return
	}
	err = en.WriteString(z.F09)
	if err != nil {
		err = msgp.WrapError(err, "F09")
		return
	}
	// write "f10"
	err = en.Append(0xa3, 0x66, 0x31, 0x30)
	if err != nil {
		return
	}
	err = en.WriteString(z.F10)
	if err != nil {
		err = msgp.WrapError(err, "F10")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NoDupManyFields) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 10
	// string "f01"
	o = append(o, 0x8a, 0xa3, 0x66, 0x30, 0x31)
	o = msgp.AppendString(o, z.F01)
	// string "f02"
	o = append(o, 0xa3, 0x66, 0x30, 0x32)
	o = msgp.AppendString(o, z.F02)
	// string "f03"
	o = append(o, 0xa3, 0x66, 0x30, 0x33)
	o = msgp.AppendString(o, z.F03)
	// string "f04"
	o = append(o, 0xa3, 0x66, 0x30, 0x34)
	o = msgp.AppendString(o, z.F04)
	// string "f05"
	o = append(o, 0xa3, 0x66, 0x30, 0x35)
	o = msgp.AppendString(o, z.F05)
	// string "f06"
	o = append(o, 0xa3, 0x66, 0x30, 0x36)
	o = msgp.AppendString(o, z.F06)
	// string "f07"
	o = append(o, 0xa3, 0x66, 0x30, 0x37)
	o = msgp.AppendString(o, z.F07)
	// string "f08"
	o = append(o, 0xa3, 0x66, 0x30, 0x38)
	o = msgp.AppendString(o, z.F08)
	// string "f09"
	o = append(o, 0xa3, 0x66, 0x30, 0x39)
	o = msgp.AppendString(o, z.F09)
	// string "f10"
	o = append(o, 0xa3, 0x66, 0x31, 0x30)
	o = msgp.AppendString(o, z.F10)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupManyFields) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [2]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "f01":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F01")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.F01, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F01")
				return
			}
		case "f02":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F02")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.F02, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F02")
				return
			}
		case "f03":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F03")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.F03, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F03")
				return
			}
		case "f04":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F04")
				return
			}
			zb0001Dup[0] |= 1 << 3
			z.F04, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F04")
				return
			}
		case "f05":
			if zb0001Dup[0]&(1<<4) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F05")
				return
			}
			zb0001Dup[0] |= 1 << 4
			z.F05, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F05")
				return
			}
		case "f06":
			if zb0001Dup[0]&(1<<5) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F06")
				return
			}
			zb0001Dup[0] |= 1 << 5
			z.F06, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F06")
				return
			}
		case "f07":
			if zb0001Dup[0]&(1<<6) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F07")
				return
			}
			zb0001Dup[0] |= 1 << 6
			z.F07, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F07")
				return
			}
		case "f08":
			if zb0001Dup[0]&(1<<7) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F08")
				return
			}
			zb0001Dup[0] |= 1 << 7
			z.F08, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F08")
				return
			}
		case "f09":
			if zb0001Dup[1]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F09")
				return
			}
			zb0001Dup[1] |= 1 << 0
			z.F09, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F09")
				return
			}
		case "f10":
			if zb0001Dup[1]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "F10")
				return
			}
			zb0001Dup[1] |= 1 << 1
			z.F10, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "F10")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NoDupManyFields) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.F01) + 4 + msgp.StringPrefixSize + len(z.F02) + 4 + msgp.StringPrefixSize + len(z.F03) + 4 + msgp.StringPrefixSize + len(z.F04) + 4 + msgp.StringPrefixSize + len(z.F05) + 4 + msgp.StringPrefixSize + len(z.F06) + 4 + msgp.StringPrefixSize + len(z.F07) + 4 + msgp.StringPrefixSize + len(z.F08) + 4 + msgp.StringPrefixSize + len(z.F09) + 4 + msgp.StringPrefixSize + len(z.F10)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupMap) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		var zb0002 string
		zb0002, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupMap) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0005, zb0006 := range z {
		err = en.WriteString(zb0005)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		err = en.WriteString(zb0006)
		if err != nil {
			err = msgp.WrapError(err, zb0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupMap) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0005, zb0006 := range z {
		o = msgp.AppendString(o, zb0005)
		o = msgp.AppendString(o, zb0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupMap) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 string
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		zb0002, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupMap) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0005, zb0006 := range z {
			_ = zb0006
			s += msgp.StringPrefixSize + len(zb0005) + msgp.StringPrefixSize + len(zb0006)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupMapComplex) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupMapComplex, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		var zb0002 NoDupInner
		var zb0005 uint32
		zb0005, err = dc.ReadMapHeader()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		var zb0005Dup [1]byte
		for zb0005 > 0 {
			zb0005--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			switch msgp.UnsafeString(field) {
			case "x":
				if zb0005Dup[0]&(1<<0) != 0 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001, "X")
					return
				}
				zb0005Dup[0] |= 1 << 0
				zb0002.X, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, zb0001, "X")
					return
				}
			case "y":
				if zb0005Dup[0]&(1<<1) != 0 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001, "Y")
					return
				}
				zb0005Dup[0] |= 1 << 1
				zb0002.Y, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Y")
					return
				}
			default:
				err = dc.Skip()
				if err != nil {
					err = msgp.WrapError(err, zb0001)
					return
				}
			}
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupMapComplex) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0006, zb0007 := range z {
		err = en.WriteString(zb0006)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		// map header, size 2
		// write "x"
		err = en.Append(0x82, 0xa1, 0x78)
		if err != nil {
			return
		}
		err = en.WriteInt(zb0007.X)
		if err != nil {
			err = msgp.WrapError(err, zb0006, "X")
			return
		}
		// write "y"
		err = en.Append(0xa1, 0x79)
		if err != nil {
			return
		}
		err = en.WriteString(zb0007.Y)
		if err != nil {
			err = msgp.WrapError(err, zb0006, "Y")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupMapComplex) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0006, zb0007 := range z {
		o = msgp.AppendString(o, zb0006)
		// map header, size 2
		// string "x"
		o = append(o, 0x82, 0xa1, 0x78)
		o = msgp.AppendInt(o, zb0007.X)
		// string "y"
		o = append(o, 0xa1, 0x79)
		o = msgp.AppendString(o, zb0007.Y)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupMapComplex) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupMapComplex, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 NoDupInner
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		var zb0005 uint32
		zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		var zb0005Dup [1]byte
		for zb0005 > 0 {
			zb0005--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			switch msgp.UnsafeString(field) {
			case "x":
				if zb0005Dup[0]&(1<<0) != 0 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001, "X")
					return
				}
				zb0005Dup[0] |= 1 << 0
				zb0002.X, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001, "X")
					return
				}
			case "y":
				if zb0005Dup[0]&(1<<1) != 0 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001, "Y")
					return
				}
				zb0005Dup[0] |= 1 << 1
				zb0002.Y, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Y")
					return
				}
			default:
				bts, err = msgp.Skip(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001)
					return
				}
			}
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupMapComplex) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0006, zb0007 := range z {
			_ = zb0007
			s += msgp.StringPrefixSize + len(zb0006) + 1 + 2 + msgp.IntSize + 2 + msgp.StringPrefixSize + len(zb0007.Y)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupMapInt) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupMapInt, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		var zb0002 int
		zb0002, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupMapInt) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0005, zb0006 := range z {
		err = en.WriteString(zb0005)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		err = en.WriteInt(zb0006)
		if err != nil {
			err = msgp.WrapError(err, zb0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupMapInt) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0005, zb0006 := range z {
		o = msgp.AppendString(o, zb0005)
		o = msgp.AppendInt(o, zb0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupMapInt) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupMapInt, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 int
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		zb0002, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupMapInt) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0005, zb0006 := range z {
			_ = zb0006
			s += msgp.StringPrefixSize + len(zb0005) + msgp.IntSize
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupNested) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Name")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "Items":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Items")
				return
			}
			zb0001Dup[0] |= 1 << 1
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Items")
				return
			}
			if z.Items == nil {
				z.Items = make(map[string]int, zb0002)
			} else if len(z.Items) > 0 {
				clear(z.Items)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Items")
					return
				}
				if _, zb0003 := z.Items[za0001]; zb0003 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "Items", za0001)
					return
				}
				var za0002 int
				za0002, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Items", za0001)
					return
				}
				z.Items[za0001] = za0002
			}
		case "Tags":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Tags")
				return
			}
			zb0001Dup[0] |= 1 << 2
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if z.Tags == nil {
				z.Tags = make(map[string]string, zb0004)
			} else if len(z.Tags) > 0 {
				clear(z.Tags)
			}
			for zb0004 > 0 {
				zb0004--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tags")
					return
				}
				if _, zb0005 := z.Tags[za0003]; zb0005 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "Tags", za0003)
					return
				}
				var za0004 string
				za0004, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0003)
					return
				}
				z.Tags[za0003] = za0004
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NoDupNested) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Name"
	err = en.Append(0x83, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "Items"
	err = en.Append(0xa5, 0x49, 0x74, 0x65, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Items)))
	if err != nil {
		err = msgp.WrapError(err, "Items")
		return
	}
	for za0001, za0002 := range z.Items {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Items")
			return
		}
		err = en.WriteInt(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Items", za0001)
			return
		}
	}
	// write "Tags"
	err = en.Append(0xa4, 0x54, 0x61, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Tags)))
	if err != nil {
		err = msgp.WrapError(err, "Tags")
		return
	}
	for za0003, za0004 := range z.Tags {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "Tags")
			return
		}
		err = en.WriteString(za0004)
		if err != nil {
			err = msgp.WrapError(err, "Tags", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NoDupNested) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Name"
	o = append(o, 0x83, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "Items"
	o = append(o, 0xa5, 0x49, 0x74, 0x65, 0x6d, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Items)))
	for za0001, za0002 := range z.Items {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendInt(o, za0002)
	}
	// string "Tags"
	o = append(o, 0xa4, 0x54, 0x61, 0x67, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Tags)))
	for za0003, za0004 := range z.Tags {
		o = msgp.AppendString(o, za0003)
		o = msgp.AppendString(o, za0004)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupNested) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Name")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "Items":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Items")
				return
			}
			zb0001Dup[0] |= 1 << 1
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Items")
				return
			}
			if z.Items == nil {
				z.Items = make(map[string]int, zb0002)
			} else if len(z.Items) > 0 {
				clear(z.Items)
			}
			for zb0002 > 0 {
				var za0002 int
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Items")
					return
				}
				if _, zb0003 := z.Items[za0001]; zb0003 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "Items", za0001)
					return
				}
				za0002, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Items", za0001)
					return
				}
				z.Items[za0001] = za0002
			}
		case "Tags":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Tags")
				return
			}
			zb0001Dup[0] |= 1 << 2
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if z.Tags == nil {
				z.Tags = make(map[string]string, zb0004)
			} else if len(z.Tags) > 0 {
				clear(z.Tags)
			}
			for zb0004 > 0 {
				var za0004 string
				zb0004--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tags")
					return
				}
				if _, zb0005 := z.Tags[za0003]; zb0005 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "Tags", za0003)
					return
				}
				za0004, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0003)
					return
				}
				z.Tags[za0003] = za0004
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NoDupNested) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.MapHeaderSize
	if z.Items != nil {
		for za0001, za0002 := range z.Items {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.IntSize
		}
	}
	s += 5 + msgp.MapHeaderSize
	if z.Tags != nil {
		for za0003, za0004 := range z.Tags {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.StringPrefixSize + len(za0004)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupOmitempty) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "required":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Required")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Required, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Required")
				return
			}
		case "optional":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Optional")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Optional, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Optional")
				return
			}
		case "flag":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Flag")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.Flag, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Flag")
				return
			}
		case "count":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Count")
				return
			}
			zb0001Dup[0] |= 1 << 3
			z.Count, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Count")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NoDupOmitempty) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.Optional == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Flag == false {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "required"
		err = en.Append(0xa8, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.Required)
		if err != nil {
			err = msgp.WrapError(err, "Required")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "optional"
			err = en.Append(0xa8, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c)
			if err != nil {
				return
			}
			err = en.WriteString(z.Optional)
			if err != nil {
				err = msgp.WrapError(err, "Optional")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "flag"
			err = en.Append(0xa4, 0x66, 0x6c, 0x61, 0x67)
			if err != nil {
				return
			}
			err = en.WriteBool(z.Flag)
			if err != nil {
				err = msgp.WrapError(err, "Flag")
				return
			}
		}
		// write "count"
		err = en.Append(0xa5, 0x63, 0x6f, 0x75, 0x6e, 0x74)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Count)
		if err != nil {
			err = msgp.WrapError(err, "Count")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NoDupOmitempty) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.Optional == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Flag == false {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "required"
		o = append(o, 0xa8, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64)
		o = msgp.AppendString(o, z.Required)
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "optional"
			o = append(o, 0xa8, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c)
			o = msgp.AppendString(o, z.Optional)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "flag"
			o = append(o, 0xa4, 0x66, 0x6c, 0x61, 0x67)
			o = msgp.AppendBool(o, z.Flag)
		}
		// string "count"
		o = append(o, 0xa5, 0x63, 0x6f, 0x75, 0x6e, 0x74)
		o = msgp.AppendInt(o, z.Count)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupOmitempty) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "required":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Required")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Required, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Required")
				return
			}
		case "optional":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Optional")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Optional, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Optional")
				return
			}
		case "flag":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Flag")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.Flag, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Flag")
				return
			}
		case "count":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Count")
				return
			}
			zb0001Dup[0] |= 1 << 3
			z.Count, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Count")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NoDupOmitempty) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.Required) + 9 + msgp.StringPrefixSize + len(z.Optional) + 5 + msgp.BoolSize + 6 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupRichTypes) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "str":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Str")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Str, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Str")
				return
			}
		case "num":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Num")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Num, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Num")
				return
			}
		case "data":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Data")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.Data, err = dc.ReadBytes(z.Data)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		case "ptr_str":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "PtrStr")
				return
			}
			zb0001Dup[0] |= 1 << 3
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "PtrStr")
					return
				}
				z.PtrStr = nil
			} else {
				if z.PtrStr == nil {
					z.PtrStr = new(string)
				}
				*z.PtrStr, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "PtrStr")
					return
				}
			}
		case "strings":
			if zb0001Dup[0]&(1<<4) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Strings")
				return
			}
			zb0001Dup[0] |= 1 << 4
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Strings")
				return
			}
			if cap(z.Strings) >= int(zb0002) {
				z.Strings = (z.Strings)[:zb0002]
			} else {
				z.Strings = make([]string, zb0002)
			}
			for za0001 := range z.Strings {
				z.Strings[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Strings", za0001)
					return
				}
			}
		case "inner":
			if zb0001Dup[0]&(1<<5) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Inner")
				return
			}
			zb0001Dup[0] |= 1 << 5
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Inner")
				return
			}
			var zb0003Dup [1]byte
			for zb0003 > 0 {
				zb0003--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Inner")
					return
				}
				switch msgp.UnsafeString(field) {
				case "x":
					if zb0003Dup[0]&(1<<0) != 0 {
						err = msgp.WrapError(msgp.ErrDuplicateEntry, "Inner", "X")
						return
					}
					zb0003Dup[0] |= 1 << 0
					z.Inner.X, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Inner", "X")
						return
					}
				case "y":
					if zb0003Dup[0]&(1<<1) != 0 {
						err = msgp.WrapError(msgp.ErrDuplicateEntry, "Inner", "Y")
						return
					}
					zb0003Dup[0] |= 1 << 1
					z.Inner.Y, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Inner", "Y")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Inner")
						return
					}
				}
			}
		case "ptr_inner":
			if zb0001Dup[0]&(1<<6) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "PtrInner")
				return
			}
			zb0001Dup[0] |= 1 << 6
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "PtrInner")
					return
				}
				z.PtrInner = nil
			} else {
				if z.PtrInner == nil {
					z.PtrInner = new(NoDupInner)
				}
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "PtrInner")
					return
				}
				var zb0004Dup [1]byte
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "PtrInner")
						return
					}
					switch msgp.UnsafeString(field) {
					case "x":
						if zb0004Dup[0]&(1<<0) != 0 {
							err = msgp.WrapError(msgp.ErrDuplicateEntry, "PtrInner", "X")
							return
						}
						zb0004Dup[0] |= 1 << 0
						z.PtrInner.X, err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "PtrInner", "X")
							return
						}
					case "y":
						if zb0004Dup[0]&(1<<1) != 0 {
							err = msgp.WrapError(msgp.ErrDuplicateEntry, "PtrInner", "Y")
							return
						}
						zb0004Dup[0] |= 1 << 1
						z.PtrInner.Y, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "PtrInner", "Y")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "PtrInner")
							return
						}
					}
				}
			}
		case "map_slice":
			if zb0001Dup[0]&(1<<7) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "MapSlice")
				return
			}
			zb0001Dup[0] |= 1 << 7
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "MapSlice")
				return
			}
			if z.MapSlice == nil {
				z.MapSlice = make(map[string][]int, zb0005)
			} else if len(z.MapSlice) > 0 {
				clear(z.MapSlice)
			}
			for zb0005 > 0 {
				zb0005--
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "MapSlice")
					return
				}
				if _, zb0006 := z.MapSlice[za0002]; zb0006 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "MapSlice", za0002)
					return
				}
				var za0003 []int
				var zb0007 uint32
				zb0007, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "MapSlice", za0002)
					return
				}
				if cap(za0003) >= int(zb0007) {
					za0003 = (za0003)[:zb0007]
				} else {
					za0003 = make([]int, zb0007)
				}
				for za0004 := range za0003 {
					za0003[za0004], err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "MapSlice", za0002, za0004)
						return
					}
				}
				z.MapSlice[za0002] = za0003
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NoDupRichTypes) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "str"
	err = en.Append(0x88, 0xa3, 0x73, 0x74, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Str)
	if err != nil {
		err = msgp.WrapError(err, "Str")
		return
	}
	// write "num"
	err = en.Append(0xa3, 0x6e, 0x75, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Num)
	if err != nil {
		err = msgp.WrapError(err, "Num")
		return
	}
	// write "data"
	err = en.Append(0xa4, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Data)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	// write "ptr_str"
	err = en.Append(0xa7, 0x70, 0x74, 0x72, 0x5f, 0x73, 0x74, 0x72)
	if err != nil {
		return
	}
	if z.PtrStr == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.PtrStr)
		if err != nil {
			err = msgp.WrapError(err, "PtrStr")
			return
		}
	}
	// write "strings"
	err = en.Append(0xa7, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Strings)))
	if err != nil {
		err = msgp.WrapError(err, "Strings")
		return
	}
	for za0001 := range z.Strings {
		err = en.WriteString(z.Strings[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Strings", za0001)
			return
		}
	}
	// write "inner"
	err = en.Append(0xa5, 0x69, 0x6e, 0x6e, 0x65, 0x72)
	if err != nil {
		return
	}
	// map header, size 2
	// write "x"
	err = en.Append(0x82, 0xa1, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Inner.X)
	if err != nil {
		err = msgp.WrapError(err, "Inner", "X")
		return
	}
	// write "y"
	err = en.Append(0xa1, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Inner.Y)
	if err != nil {
		err = msgp.WrapError(err, "Inner", "Y")
		return
	}
	// write "ptr_inner"
	err = en.Append(0xa9, 0x70, 0x74, 0x72, 0x5f, 0x69, 0x6e, 0x6e, 0x65, 0x72)
	if err != nil {
		return
	}
	if z.PtrInner == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 2
		// write "x"
		err = en.Append(0x82, 0xa1, 0x78)
		if err != nil {
			return
		}
		err = en.WriteInt(z.PtrInner.X)
		if err != nil {
			err = msgp.WrapError(err, "PtrInner", "X")
			return
		}
		// write "y"
		err = en.Append(0xa1, 0x79)
		if err != nil {
			return
		}
		err = en.WriteString(z.PtrInner.Y)
		if err != nil {
			err = msgp.WrapError(err, "PtrInner", "Y")
			return
		}
	}
	// write "map_slice"
	err = en.Append(0xa9, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.MapSlice)))
	if err != nil {
		err = msgp.WrapError(err, "MapSlice")
		return
	}
	for za0002, za0003 := range z.MapSlice {
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "MapSlice")
			return
		}
		err = en.WriteArrayHeader(uint32(len(za0003)))
		if err != nil {
			err = msgp.WrapError(err, "MapSlice", za0002)
			return
		}
		for za0004 := range za0003 {
			err = en.WriteInt(za0003[za0004])
			if err != nil {
				err = msgp.WrapError(err, "MapSlice", za0002, za0004)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NoDupRichTypes) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "str"
	o = append(o, 0x88, 0xa3, 0x73, 0x74, 0x72)
	o = msgp.AppendString(o, z.Str)
	// string "num"
	o = append(o, 0xa3, 0x6e, 0x75, 0x6d)
	o = msgp.AppendFloat64(o, z.Num)
	// string "data"
	o = append(o, 0xa4, 0x64, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Data)
	// string "ptr_str"
	o = append(o, 0xa7, 0x70, 0x74, 0x72, 0x5f, 0x73, 0x74, 0x72)
	if z.PtrStr == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.PtrStr)
	}
	// string "strings"
	o = append(o, 0xa7, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Strings)))
	for za0001 := range z.Strings {
		o = msgp.AppendString(o, z.Strings[za0001])
	}
	// string "inner"
	o = append(o, 0xa5, 0x69, 0x6e, 0x6e, 0x65, 0x72)
	// map header, size 2
	// string "x"
	o = append(o, 0x82, 0xa1, 0x78)
	o = msgp.AppendInt(o, z.Inner.X)
	// string "y"
	o = append(o, 0xa1, 0x79)
	o = msgp.AppendString(o, z.Inner.Y)
	// string "ptr_inner"
	o = append(o, 0xa9, 0x70, 0x74, 0x72, 0x5f, 0x69, 0x6e, 0x6e, 0x65, 0x72)
	if z.PtrInner == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 2
		// string "x"
		o = append(o, 0x82, 0xa1, 0x78)
		o = msgp.AppendInt(o, z.PtrInner.X)
		// string "y"
		o = append(o, 0xa1, 0x79)
		o = msgp.AppendString(o, z.PtrInner.Y)
	}
	// string "map_slice"
	o = append(o, 0xa9, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65)
	o = msgp.AppendMapHeader(o, uint32(len(z.MapSlice)))
	for za0002, za0003 := range z.MapSlice {
		o = msgp.AppendString(o, za0002)
		o = msgp.AppendArrayHeader(o, uint32(len(za0003)))
		for za0004 := range za0003 {
			o = msgp.AppendInt(o, za0003[za0004])
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupRichTypes) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "str":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Str")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Str, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Str")
				return
			}
		case "num":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Num")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Num, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Num")
				return
			}
		case "data":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Data")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		case "ptr_str":
			if zb0001Dup[0]&(1<<3) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "PtrStr")
				return
			}
			zb0001Dup[0] |= 1 << 3
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.PtrStr = nil
			} else {
				if z.PtrStr == nil {
					z.PtrStr = new(string)
				}
				*z.PtrStr, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PtrStr")
					return
				}
			}
		case "strings":
			if zb0001Dup[0]&(1<<4) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Strings")
				return
			}
			zb0001Dup[0] |= 1 << 4
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Strings")
				return
			}
			if cap(z.Strings) >= int(zb0002) {
				z.Strings = (z.Strings)[:zb0002]
			} else {
				z.Strings = make([]string, zb0002)
			}
			for za0001 := range z.Strings {
				z.Strings[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Strings", za0001)
					return
				}
			}
		case "inner":
			if zb0001Dup[0]&(1<<5) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Inner")
				return
			}
			zb0001Dup[0] |= 1 << 5
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Inner")
				return
			}
			var zb0003Dup [1]byte
			for zb0003 > 0 {
				zb0003--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Inner")
					return
				}
				switch msgp.UnsafeString(field) {
				case "x":
					if zb0003Dup[0]&(1<<0) != 0 {
						err = msgp.WrapError(msgp.ErrDuplicateEntry, "Inner", "X")
						return
					}
					zb0003Dup[0] |= 1 << 0
					z.Inner.X, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Inner", "X")
						return
					}
				case "y":
					if zb0003Dup[0]&(1<<1) != 0 {
						err = msgp.WrapError(msgp.ErrDuplicateEntry, "Inner", "Y")
						return
					}
					zb0003Dup[0] |= 1 << 1
					z.Inner.Y, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Inner", "Y")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Inner")
						return
					}
				}
			}
		case "ptr_inner":
			if zb0001Dup[0]&(1<<6) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "PtrInner")
				return
			}
			zb0001Dup[0] |= 1 << 6
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.PtrInner = nil
			} else {
				if z.PtrInner == nil {
					z.PtrInner = new(NoDupInner)
				}
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PtrInner")
					return
				}
				var zb0004Dup [1]byte
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "PtrInner")
						return
					}
					switch msgp.UnsafeString(field) {
					case "x":
						if zb0004Dup[0]&(1<<0) != 0 {
							err = msgp.WrapError(msgp.ErrDuplicateEntry, "PtrInner", "X")
							return
						}
						zb0004Dup[0] |= 1 << 0
						z.PtrInner.X, bts, err = msgp.ReadIntBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "PtrInner", "X")
							return
						}
					case "y":
						if zb0004Dup[0]&(1<<1) != 0 {
							err = msgp.WrapError(msgp.ErrDuplicateEntry, "PtrInner", "Y")
							return
						}
						zb0004Dup[0] |= 1 << 1
						z.PtrInner.Y, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "PtrInner", "Y")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "PtrInner")
							return
						}
					}
				}
			}
		case "map_slice":
			if zb0001Dup[0]&(1<<7) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "MapSlice")
				return
			}
			zb0001Dup[0] |= 1 << 7
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MapSlice")
				return
			}
			if z.MapSlice == nil {
				z.MapSlice = make(map[string][]int, zb0005)
			} else if len(z.MapSlice) > 0 {
				clear(z.MapSlice)
			}
			for zb0005 > 0 {
				var za0003 []int
				zb0005--
				var za0002 string
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MapSlice")
					return
				}
				if _, zb0006 := z.MapSlice[za0002]; zb0006 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "MapSlice", za0002)
					return
				}
				var zb0007 uint32
				zb0007, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MapSlice", za0002)
					return
				}
				if cap(za0003) >= int(zb0007) {
					za0003 = (za0003)[:zb0007]
				} else {
					za0003 = make([]int, zb0007)
				}
				for za0004 := range za0003 {
					za0003[za0004], bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "MapSlice", za0002, za0004)
						return
					}
				}
				z.MapSlice[za0002] = za0003
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NoDupRichTypes) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.Str) + 4 + msgp.Float64Size + 5 + msgp.BytesPrefixSize + len(z.Data) + 8
	if z.PtrStr == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.PtrStr)
	}
	s += 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Strings {
		s += msgp.StringPrefixSize + len(z.Strings[za0001])
	}
	s += 6 + 1 + 2 + msgp.IntSize + 2 + msgp.StringPrefixSize + len(z.Inner.Y) + 10
	if z.PtrInner == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 2 + msgp.IntSize + 2 + msgp.StringPrefixSize + len(z.PtrInner.Y)
	}
	s += 10 + msgp.MapHeaderSize
	if z.MapSlice != nil {
		for za0002, za0003 := range z.MapSlice {
			_ = za0003
			s += msgp.StringPrefixSize + len(za0002) + msgp.ArrayHeaderSize + (len(za0003) * (msgp.IntSize))
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupSimple) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Foo":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Foo")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Foo, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Foo")
				return
			}
		case "Bar":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Bar")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Bar, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Bar")
				return
			}
		case "Baz":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Baz")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.Baz, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Baz")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupSimple) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Foo"
	err = en.Append(0x83, 0xa3, 0x46, 0x6f, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteString(z.Foo)
	if err != nil {
		err = msgp.WrapError(err, "Foo")
		return
	}
	// write "Bar"
	err = en.Append(0xa3, 0x42, 0x61, 0x72)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Bar)
	if err != nil {
		err = msgp.WrapError(err, "Bar")
		return
	}
	// write "Baz"
	err = en.Append(0xa3, 0x42, 0x61, 0x7a)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Baz)
	if err != nil {
		err = msgp.WrapError(err, "Baz")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupSimple) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Foo"
	o = append(o, 0x83, 0xa3, 0x46, 0x6f, 0x6f)
	o = msgp.AppendString(o, z.Foo)
	// string "Bar"
	o = append(o, 0xa3, 0x42, 0x61, 0x72)
	o = msgp.AppendInt(o, z.Bar)
	// string "Baz"
	o = append(o, 0xa3, 0x42, 0x61, 0x7a)
	o = msgp.AppendBool(o, z.Baz)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupSimple) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Foo":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Foo")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Foo, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Foo")
				return
			}
		case "Bar":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Bar")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Bar, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bar")
				return
			}
		case "Baz":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Baz")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.Baz, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Baz")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupSimple) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.Foo) + 4 + msgp.IntSize + 4 + msgp.BoolSize
	return
}
