// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *NoDupShimKey) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = noDupShimDec(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupShimKey) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(noDupShimEnc(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupShimKey) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, noDupShimEnc(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupShimKey) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = noDupShimDec(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupShimKey) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(noDupShimEnc(z))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupShimMap) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupShimMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		var zb0002 int
		zb0002, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		var zb0001Tmp NoDupShimKey
		zb0001Tmp = noDupShimDec(zb0001)
		if _, zb0004 := (*z)[zb0001Tmp]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		(*z)[zb0001Tmp] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupShimMap) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0005, zb0006 := range z {
		err = en.WriteString(noDupShimEnc(zb0005))
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		err = en.WriteInt(zb0006)
		if err != nil {
			err = msgp.WrapError(err, zb0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupShimMap) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0005, zb0006 := range z {
		o = msgp.AppendString(o, noDupShimEnc(zb0005))
		o = msgp.AppendInt(o, zb0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupShimMap) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupShimMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 int
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		zb0002, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		var zb0001Tmp NoDupShimKey
		zb0001Tmp = noDupShimDec(zb0001)
		if _, zb0004 := (*z)[zb0001Tmp]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		(*z)[zb0001Tmp] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupShimMap) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0005, zb0006 := range z {
			_ = zb0006
			s += msgp.StringPrefixSize + len(noDupShimEnc(zb0005)) + msgp.IntSize
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupShimStruct) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Name")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "data":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Data")
				return
			}
			zb0001Dup[0] |= 1 << 1
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
			if z.Data == nil {
				z.Data = make(map[NoDupShimKey]string, zb0002)
			} else if len(z.Data) > 0 {
				clear(z.Data)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Data")
					return
				}
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Data", za0001)
					return
				}
				var za0001Tmp NoDupShimKey
				za0001Tmp = noDupShimDec(za0001)
				if _, zb0003 := z.Data[za0001Tmp]; zb0003 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "Data", za0001)
					return
				}
				z.Data[za0001Tmp] = za0002
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NoDupShimStruct) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "name"
	err = en.Append(0x82, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "data"
	err = en.Append(0xa4, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Data)))
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	for za0001, za0002 := range z.Data {
		err = en.WriteString(noDupShimEnc(za0001))
		if err != nil {
			err = msgp.WrapError(err, "Data")
			return
		}
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Data", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NoDupShimStruct) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "name"
	o = append(o, 0x82, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "data"
	o = append(o, 0xa4, 0x64, 0x61, 0x74, 0x61)
	o = msgp.AppendMapHeader(o, uint32(len(z.Data)))
	for za0001, za0002 := range z.Data {
		o = msgp.AppendString(o, noDupShimEnc(za0001))
		o = msgp.AppendString(o, za0002)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupShimStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Name")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "data":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Data")
				return
			}
			zb0001Dup[0] |= 1 << 1
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
			if z.Data == nil {
				z.Data = make(map[NoDupShimKey]string, zb0002)
			} else if len(z.Data) > 0 {
				clear(z.Data)
			}
			for zb0002 > 0 {
				var za0002 string
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Data")
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Data", za0001)
					return
				}
				var za0001Tmp NoDupShimKey
				za0001Tmp = noDupShimDec(za0001)
				if _, zb0003 := z.Data[za0001Tmp]; zb0003 {
					err = msgp.WrapError(msgp.ErrDuplicateEntry, "Data", za0001)
					return
				}
				z.Data[za0001Tmp] = za0002
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NoDupShimStruct) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 5 + msgp.MapHeaderSize
	if z.Data != nil {
		for za0001, za0002 := range z.Data {
			_ = za0002
			s += msgp.StringPrefixSize + len(noDupShimEnc(za0001)) + msgp.StringPrefixSize + len(za0002)
		}
	}
	return
}
