// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *NoDupTargeted) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "alpha":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Alpha")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Alpha, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Alpha")
				return
			}
		case "beta":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Beta")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Beta, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Beta")
				return
			}
		case "gamma":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Gamma")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.Gamma, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Gamma")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupTargeted) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "alpha"
	err = en.Append(0x83, 0xa5, 0x61, 0x6c, 0x70, 0x68, 0x61)
	if err != nil {
		return
	}
	err = en.WriteString(z.Alpha)
	if err != nil {
		err = msgp.WrapError(err, "Alpha")
		return
	}
	// write "beta"
	err = en.Append(0xa4, 0x62, 0x65, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Beta)
	if err != nil {
		err = msgp.WrapError(err, "Beta")
		return
	}
	// write "gamma"
	err = en.Append(0xa5, 0x67, 0x61, 0x6d, 0x6d, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Gamma)
	if err != nil {
		err = msgp.WrapError(err, "Gamma")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupTargeted) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "alpha"
	o = append(o, 0x83, 0xa5, 0x61, 0x6c, 0x70, 0x68, 0x61)
	o = msgp.AppendString(o, z.Alpha)
	// string "beta"
	o = append(o, 0xa4, 0x62, 0x65, 0x74, 0x61)
	o = msgp.AppendInt(o, z.Beta)
	// string "gamma"
	o = append(o, 0xa5, 0x67, 0x61, 0x6d, 0x6d, 0x61)
	o = msgp.AppendBool(o, z.Gamma)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupTargeted) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Dup [1]byte
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "alpha":
			if zb0001Dup[0]&(1<<0) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Alpha")
				return
			}
			zb0001Dup[0] |= 1 << 0
			z.Alpha, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Alpha")
				return
			}
		case "beta":
			if zb0001Dup[0]&(1<<1) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Beta")
				return
			}
			zb0001Dup[0] |= 1 << 1
			z.Beta, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Beta")
				return
			}
		case "gamma":
			if zb0001Dup[0]&(1<<2) != 0 {
				err = msgp.WrapError(msgp.ErrDuplicateEntry, "Gamma")
				return
			}
			zb0001Dup[0] |= 1 << 2
			z.Gamma, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Gamma")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupTargeted) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Alpha) + 5 + msgp.IntSize + 6 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupTargetedMap) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupTargetedMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		var zb0002 int
		zb0002, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupTargetedMap) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0005, zb0006 := range z {
		err = en.WriteString(zb0005)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		err = en.WriteInt(zb0006)
		if err != nil {
			err = msgp.WrapError(err, zb0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupTargetedMap) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0005, zb0006 := range z {
		o = msgp.AppendString(o, zb0005)
		o = msgp.AppendInt(o, zb0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupTargetedMap) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupTargetedMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 int
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		if _, zb0004 := (*z)[zb0001]; zb0004 {
			err = msgp.WrapError(msgp.ErrDuplicateEntry, zb0001)
			return
		}
		zb0002, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupTargetedMap) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0005, zb0006 := range z {
			_ = zb0006
			s += msgp.StringPrefixSize + len(zb0005) + msgp.IntSize
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupUntargeted) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "alpha":
			z.Alpha, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Alpha")
				return
			}
		case "beta":
			z.Beta, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Beta")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupUntargeted) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "alpha"
	err = en.Append(0x82, 0xa5, 0x61, 0x6c, 0x70, 0x68, 0x61)
	if err != nil {
		return
	}
	err = en.WriteString(z.Alpha)
	if err != nil {
		err = msgp.WrapError(err, "Alpha")
		return
	}
	// write "beta"
	err = en.Append(0xa4, 0x62, 0x65, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Beta)
	if err != nil {
		err = msgp.WrapError(err, "Beta")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupUntargeted) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "alpha"
	o = append(o, 0x82, 0xa5, 0x61, 0x6c, 0x70, 0x68, 0x61)
	o = msgp.AppendString(o, z.Alpha)
	// string "beta"
	o = append(o, 0xa4, 0x62, 0x65, 0x74, 0x61)
	o = msgp.AppendInt(o, z.Beta)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupUntargeted) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "alpha":
			z.Alpha, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Alpha")
				return
			}
		case "beta":
			z.Beta, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Beta")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupUntargeted) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Alpha) + 5 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NoDupUntargetedMap) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupUntargetedMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		var zb0002 string
		zb0002, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z NoDupUntargetedMap) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0004, zb0005 := range z {
		err = en.WriteString(zb0004)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		err = en.WriteString(zb0005)
		if err != nil {
			err = msgp.WrapError(err, zb0004)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z NoDupUntargetedMap) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0004, zb0005 := range z {
		o = msgp.AppendString(o, zb0004)
		o = msgp.AppendString(o, zb0005)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NoDupUntargetedMap) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(NoDupUntargetedMap, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 string
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		zb0002, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NoDupUntargetedMap) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0004, zb0005 := range z {
			_ = zb0005
			s += msgp.StringPrefixSize + len(zb0004) + msgp.StringPrefixSize + len(zb0005)
		}
	}
	return
}
