// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package _generated

import (
	"encoding/json"
	"time"

	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CompatibleArray8) DecodeMsg(dc *msgp.Reader) (err error) {
	err = dc.ReadExactBytes((z)[:])
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CompatibleArray8) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteBytes((z)[:])
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CompatibleArray8) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendBytes(o, (z)[:])
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleArray8) UnmarshalMsg(bts []byte) (o []byte, err error) {
	bts, err = msgp.ReadExactBytes(bts, (z)[:])
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompatibleArray8) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize + (8 * (msgp.ByteSize))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleFloat32) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 float32
		zb0001, err = dc.ReadFloat32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CompatibleFloat32(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CompatibleFloat32) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteFloat32(float32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CompatibleFloat32) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendFloat32(o, float32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleFloat32) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 float32
		zb0001, bts, err = msgp.ReadFloat32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CompatibleFloat32(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CompatibleFloat32) Msgsize() (s int) {
	s = msgp.Float32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleFloat64) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 float64
		zb0001, err = dc.ReadFloat64()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CompatibleFloat64(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CompatibleFloat64) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteFloat64(float64(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CompatibleFloat64) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendFloat64(o, float64(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleFloat64) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 float64
		zb0001, bts, err = msgp.ReadFloat64Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CompatibleFloat64(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CompatibleFloat64) Msgsize() (s int) {
	s = msgp.Float64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleInt) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int
		zb0001, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CompatibleInt(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CompatibleInt) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt(int(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CompatibleInt) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleInt) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int
		zb0001, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CompatibleInt(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CompatibleInt) Msgsize() (s int) {
	s = msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleMapString) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(CompatibleMapString, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		var zb0002 string
		zb0002, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CompatibleMapString) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0004, zb0005 := range z {
		err = en.WriteString(zb0004)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		err = en.WriteString(zb0005)
		if err != nil {
			err = msgp.WrapError(err, zb0004)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CompatibleMapString) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for zb0004, zb0005 := range z {
		o = msgp.AppendString(o, zb0004)
		o = msgp.AppendString(o, zb0005)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleMapString) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(CompatibleMapString, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 string
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		zb0002, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CompatibleMapString) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0004, zb0005 := range z {
			_ = zb0005
			s += msgp.StringPrefixSize + len(zb0004) + msgp.StringPrefixSize + len(zb0005)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleSliceInt) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(CompatibleSliceInt, zb0002)
	}
	for zb0001 := range *z {
		err = (*CompatibleInt)(&(*z)[zb0001]).DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CompatibleSliceInt) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0003 := range z {
		err = (*CompatibleInt)(&z[zb0003]).EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CompatibleSliceInt) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0003 := range z {
		o, err = (*CompatibleInt)(&z[zb0003]).MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, zb0003)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleSliceInt) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(CompatibleSliceInt, zb0002)
	}
	for zb0001 := range *z {
		bts, err = (*CompatibleInt)(&(*z)[zb0001]).UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CompatibleSliceInt) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0003 := range z {
		s += (*CompatibleInt)(&z[zb0003]).Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleStructA) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "StructB":
			err = (*CompatibleStructB)(&z.StructB).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "StructB")
				return
			}
		case "Int":
			err = (*CompatibleInt)(&z.Int).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Int")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CompatibleStructA) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "StructB"
	err = en.Append(0x82, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x42)
	if err != nil {
		return
	}
	err = (*CompatibleStructB)(&z.StructB).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "StructB")
		return
	}
	// write "Int"
	err = en.Append(0xa3, 0x49, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = (*CompatibleInt)(&z.Int).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Int")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CompatibleStructA) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "StructB"
	o = append(o, 0x82, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x42)
	o, err = (*CompatibleStructB)(&z.StructB).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "StructB")
		return
	}
	// string "Int"
	o = append(o, 0xa3, 0x49, 0x6e, 0x74)
	o, err = (*CompatibleInt)(&z.Int).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Int")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleStructA) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "StructB":
			bts, err = (*CompatibleStructB)(&z.StructB).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "StructB")
				return
			}
		case "Int":
			bts, err = (*CompatibleInt)(&z.Int).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Int")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompatibleStructA) Msgsize() (s int) {
	s = 1 + 8 + (*CompatibleStructB)(&z.StructB).Msgsize() + 4 + (*CompatibleInt)(&z.Int).Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleStructB) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "StructC":
			err = (*CompatibleStructC)(&z.StructC).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "StructC")
				return
			}
		case "Any":
			{
				var zb0002 interface{}
				zb0002, err = dc.ReadIntf()
				if err != nil {
					err = msgp.WrapError(err, "Any")
					return
				}
				z.Any = Any(zb0002)
			}
		case "Array8":
			err = (*CompatibleArray8)(&z.Array8).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Array8")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CompatibleStructB) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "StructC"
	err = en.Append(0x83, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x43)
	if err != nil {
		return
	}
	err = (*CompatibleStructC)(&z.StructC).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "StructC")
		return
	}
	// write "Any"
	err = en.Append(0xa3, 0x41, 0x6e, 0x79)
	if err != nil {
		return
	}
	err = en.WriteIntf(interface{}(z.Any))
	if err != nil {
		err = msgp.WrapError(err, "Any")
		return
	}
	// write "Array8"
	err = en.Append(0xa6, 0x41, 0x72, 0x72, 0x61, 0x79, 0x38)
	if err != nil {
		return
	}
	err = (*CompatibleArray8)(&z.Array8).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Array8")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CompatibleStructB) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "StructC"
	o = append(o, 0x83, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x43)
	o, err = (*CompatibleStructC)(&z.StructC).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "StructC")
		return
	}
	// string "Any"
	o = append(o, 0xa3, 0x41, 0x6e, 0x79)
	o, err = msgp.AppendIntf(o, interface{}(z.Any))
	if err != nil {
		err = msgp.WrapError(err, "Any")
		return
	}
	// string "Array8"
	o = append(o, 0xa6, 0x41, 0x72, 0x72, 0x61, 0x79, 0x38)
	o, err = (*CompatibleArray8)(&z.Array8).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Array8")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleStructB) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "StructC":
			bts, err = (*CompatibleStructC)(&z.StructC).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "StructC")
				return
			}
		case "Any":
			{
				var zb0002 interface{}
				zb0002, bts, err = msgp.ReadIntfBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Any")
					return
				}
				z.Any = Any(zb0002)
			}
		case "Array8":
			bts, err = (*CompatibleArray8)(&z.Array8).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Array8")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompatibleStructB) Msgsize() (s int) {
	s = 1 + 8 + (*CompatibleStructC)(&z.StructC).Msgsize() + 4 + msgp.GuessSize(interface{}(z.Any)) + 7 + (*CompatibleArray8)(&z.Array8).Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleStructC) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "StructD":
			err = (*CompatibleStructD)(&z.StructD).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "StructD")
				return
			}
		case "Float64":
			err = (*CompatibleFloat32)(&z.Float64).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Float64")
				return
			}
		case "Float32":
			err = (*CompatibleFloat64)(&z.Float32).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Float32")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CompatibleStructC) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "StructD"
	err = en.Append(0x83, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x44)
	if err != nil {
		return
	}
	err = (*CompatibleStructD)(&z.StructD).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "StructD")
		return
	}
	// write "Float64"
	err = en.Append(0xa7, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34)
	if err != nil {
		return
	}
	err = (*CompatibleFloat32)(&z.Float64).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Float64")
		return
	}
	// write "Float32"
	err = en.Append(0xa7, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32)
	if err != nil {
		return
	}
	err = (*CompatibleFloat64)(&z.Float32).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Float32")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CompatibleStructC) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "StructD"
	o = append(o, 0x83, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x44)
	o, err = (*CompatibleStructD)(&z.StructD).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "StructD")
		return
	}
	// string "Float64"
	o = append(o, 0xa7, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34)
	o, err = (*CompatibleFloat32)(&z.Float64).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Float64")
		return
	}
	// string "Float32"
	o = append(o, 0xa7, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32)
	o, err = (*CompatibleFloat64)(&z.Float32).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Float32")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleStructC) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "StructD":
			bts, err = (*CompatibleStructD)(&z.StructD).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "StructD")
				return
			}
		case "Float64":
			bts, err = (*CompatibleFloat32)(&z.Float64).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Float64")
				return
			}
		case "Float32":
			bts, err = (*CompatibleFloat64)(&z.Float32).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Float32")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompatibleStructC) Msgsize() (s int) {
	s = 1 + 8 + (*CompatibleStructD)(&z.StructD).Msgsize() + 8 + (*CompatibleFloat32)(&z.Float64).Msgsize() + 8 + (*CompatibleFloat64)(&z.Float32).Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleStructD) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Time":
			{
				var zb0002 time.Time
				zb0002, err = dc.ReadTime()
				if err != nil {
					err = msgp.WrapError(err, "Time")
					return
				}
				z.Time = Time(zb0002)
			}
		case "Duration":
			{
				var zb0003 time.Duration
				zb0003, err = dc.ReadDuration()
				if err != nil {
					err = msgp.WrapError(err, "Duration")
					return
				}
				z.Duration = Duration(zb0003)
			}
		case "MapString":
			err = (*CompatibleMapString)(&z.MapString).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "MapString")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CompatibleStructD) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Time"
	err = en.Append(0x83, 0xa4, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(time.Time(z.Time))
	if err != nil {
		err = msgp.WrapError(err, "Time")
		return
	}
	// write "Duration"
	err = en.Append(0xa8, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteDuration(time.Duration(z.Duration))
	if err != nil {
		err = msgp.WrapError(err, "Duration")
		return
	}
	// write "MapString"
	err = en.Append(0xa9, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = (*CompatibleMapString)(&z.MapString).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "MapString")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CompatibleStructD) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Time"
	o = append(o, 0x83, 0xa4, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, time.Time(z.Time))
	// string "Duration"
	o = append(o, 0xa8, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendDuration(o, time.Duration(z.Duration))
	// string "MapString"
	o = append(o, 0xa9, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67)
	o, err = (*CompatibleMapString)(&z.MapString).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "MapString")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleStructD) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Time":
			{
				var zb0002 time.Time
				zb0002, bts, err = msgp.ReadTimeBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Time")
					return
				}
				z.Time = Time(zb0002)
			}
		case "Duration":
			{
				var zb0003 time.Duration
				zb0003, bts, err = msgp.ReadDurationBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Duration")
					return
				}
				z.Duration = Duration(zb0003)
			}
		case "MapString":
			bts, err = (*CompatibleMapString)(&z.MapString).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "MapString")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompatibleStructD) Msgsize() (s int) {
	s = 1 + 5 + msgp.TimeSize + 9 + msgp.DurationSize + 10 + (*CompatibleMapString)(&z.MapString).Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleStructI) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Int":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Int")
					return
				}
				z.Int = nil
			} else {
				if z.Int == nil {
					z.Int = new(Int)
				}
				err = (*CompatibleInt)(z.Int).DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Int")
					return
				}
			}
		case "Uint":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Uint")
					return
				}
				z.Uint = nil
			} else {
				if z.Uint == nil {
					z.Uint = new(Uint)
				}
				{
					var zb0002 uint
					zb0002, err = dc.ReadUint()
					if err != nil {
						err = msgp.WrapError(err, "Uint")
						return
					}
					*z.Uint = Uint(zb0002)
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CompatibleStructI) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Int"
	err = en.Append(0x82, 0xa3, 0x49, 0x6e, 0x74)
	if err != nil {
		return
	}
	if z.Int == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = (*CompatibleInt)(z.Int).EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Int")
			return
		}
	}
	// write "Uint"
	err = en.Append(0xa4, 0x55, 0x69, 0x6e, 0x74)
	if err != nil {
		return
	}
	if z.Uint == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteUint(uint(*z.Uint))
		if err != nil {
			err = msgp.WrapError(err, "Uint")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CompatibleStructI) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Int"
	o = append(o, 0x82, 0xa3, 0x49, 0x6e, 0x74)
	if z.Int == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = (*CompatibleInt)(z.Int).MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Int")
			return
		}
	}
	// string "Uint"
	o = append(o, 0xa4, 0x55, 0x69, 0x6e, 0x74)
	if z.Uint == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendUint(o, uint(*z.Uint))
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleStructI) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Int":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Int = nil
			} else {
				if z.Int == nil {
					z.Int = new(Int)
				}
				bts, err = (*CompatibleInt)(z.Int).UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Int")
					return
				}
			}
		case "Uint":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Uint = nil
			} else {
				if z.Uint == nil {
					z.Uint = new(Uint)
				}
				{
					var zb0002 uint
					zb0002, bts, err = msgp.ReadUintBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Uint")
						return
					}
					*z.Uint = Uint(zb0002)
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompatibleStructI) Msgsize() (s int) {
	s = 1 + 4
	if z.Int == nil {
		s += msgp.NilSize
	} else {
		s += (*CompatibleInt)(z.Int).Msgsize()
	}
	s += 5
	if z.Uint == nil {
		s += msgp.NilSize
	} else {
		s += msgp.UintSize
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CompatibleStructS) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Slice":
			err = (*CompatibleSliceInt)(&z.Slice).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Slice")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CompatibleStructS) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "Slice"
	err = en.Append(0x81, 0xa5, 0x53, 0x6c, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = (*CompatibleSliceInt)(&z.Slice).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Slice")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CompatibleStructS) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "Slice"
	o = append(o, 0x81, 0xa5, 0x53, 0x6c, 0x69, 0x63, 0x65)
	o, err = (*CompatibleSliceInt)(&z.Slice).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Slice")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompatibleStructS) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Slice":
			bts, err = (*CompatibleSliceInt)(&z.Slice).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Slice")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompatibleStructS) Msgsize() (s int) {
	s = 1 + 6 + (*CompatibleSliceInt)(&z.Slice).Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Dummy) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "StructA":
			err = (*CompatibleStructA)(&z.StructA).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "StructA")
				return
			}
		case "StructI":
			err = (*CompatibleStructI)(&z.StructI).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "StructI")
				return
			}
		case "StructS":
			err = (*CompatibleStructS)(&z.StructS).DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "StructS")
				return
			}
		case "Array16":
			err = dc.ReadExactBytes((z.Array16)[:])
			if err != nil {
				err = msgp.WrapError(err, "Array16")
				return
			}
		case "Uint":
			{
				var zb0002 uint
				zb0002, err = dc.ReadUint()
				if err != nil {
					err = msgp.WrapError(err, "Uint")
					return
				}
				z.Uint = Uint(zb0002)
			}
		case "String":
			{
				var zb0003 string
				zb0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "String")
					return
				}
				z.String = String(zb0003)
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Dummy) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "StructA"
	err = en.Append(0x86, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x41)
	if err != nil {
		return
	}
	err = (*CompatibleStructA)(&z.StructA).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "StructA")
		return
	}
	// write "StructI"
	err = en.Append(0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x49)
	if err != nil {
		return
	}
	err = (*CompatibleStructI)(&z.StructI).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "StructI")
		return
	}
	// write "StructS"
	err = en.Append(0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x53)
	if err != nil {
		return
	}
	err = (*CompatibleStructS)(&z.StructS).EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "StructS")
		return
	}
	// write "Array16"
	err = en.Append(0xa7, 0x41, 0x72, 0x72, 0x61, 0x79, 0x31, 0x36)
	if err != nil {
		return
	}
	err = en.WriteBytes((z.Array16)[:])
	if err != nil {
		err = msgp.WrapError(err, "Array16")
		return
	}
	// write "Uint"
	err = en.Append(0xa4, 0x55, 0x69, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint(uint(z.Uint))
	if err != nil {
		err = msgp.WrapError(err, "Uint")
		return
	}
	// write "String"
	err = en.Append(0xa6, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteString(string(z.String))
	if err != nil {
		err = msgp.WrapError(err, "String")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Dummy) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "StructA"
	o = append(o, 0x86, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x41)
	o, err = (*CompatibleStructA)(&z.StructA).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "StructA")
		return
	}
	// string "StructI"
	o = append(o, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x49)
	o, err = (*CompatibleStructI)(&z.StructI).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "StructI")
		return
	}
	// string "StructS"
	o = append(o, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x53)
	o, err = (*CompatibleStructS)(&z.StructS).MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "StructS")
		return
	}
	// string "Array16"
	o = append(o, 0xa7, 0x41, 0x72, 0x72, 0x61, 0x79, 0x31, 0x36)
	o = msgp.AppendBytes(o, (z.Array16)[:])
	// string "Uint"
	o = append(o, 0xa4, 0x55, 0x69, 0x6e, 0x74)
	o = msgp.AppendUint(o, uint(z.Uint))
	// string "String"
	o = append(o, 0xa6, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67)
	o = msgp.AppendString(o, string(z.String))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Dummy) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "StructA":
			bts, err = (*CompatibleStructA)(&z.StructA).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "StructA")
				return
			}
		case "StructI":
			bts, err = (*CompatibleStructI)(&z.StructI).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "StructI")
				return
			}
		case "StructS":
			bts, err = (*CompatibleStructS)(&z.StructS).UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "StructS")
				return
			}
		case "Array16":
			bts, err = msgp.ReadExactBytes(bts, (z.Array16)[:])
			if err != nil {
				err = msgp.WrapError(err, "Array16")
				return
			}
		case "Uint":
			{
				var zb0002 uint
				zb0002, bts, err = msgp.ReadUintBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Uint")
					return
				}
				z.Uint = Uint(zb0002)
			}
		case "String":
			{
				var zb0003 string
				zb0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "String")
					return
				}
				z.String = String(zb0003)
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Dummy) Msgsize() (s int) {
	s = 1 + 8 + (*CompatibleStructA)(&z.StructA).Msgsize() + 8 + (*CompatibleStructI)(&z.StructI).Msgsize() + 8 + (*CompatibleStructS)(&z.StructS).Msgsize() + 8 + msgp.ArrayHeaderSize + (16 * (msgp.ByteSize)) + 5 + msgp.UintSize + 7 + msgp.StringPrefixSize + len(string(z.String))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NumberJSONSampleReplace) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Single":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Single")
					return
				}
				z.Single = json.Number(zb0002)
			}
		case "Array":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Array")
				return
			}
			if cap(z.Array) >= int(zb0003) {
				z.Array = (z.Array)[:zb0003]
			} else {
				z.Array = make([]json.Number, zb0003)
			}
			for za0001 := range z.Array {
				{
					var zb0004 string
					zb0004, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Array", za0001)
						return
					}
					z.Array[za0001] = json.Number(zb0004)
				}
			}
		case "Map":
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Map")
				return
			}
			if z.Map == nil {
				z.Map = make(map[string]json.Number, zb0005)
			} else if len(z.Map) > 0 {
				clear(z.Map)
			}
			for zb0005 > 0 {
				zb0005--
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Map")
					return
				}
				var za0003 json.Number
				{
					var zb0006 string
					zb0006, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Map", za0002)
						return
					}
					za0003 = json.Number(zb0006)
				}
				z.Map[za0002] = za0003
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NumberJSONSampleReplace) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Single"
	err = en.Append(0x83, 0xa6, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(string(z.Single))
	if err != nil {
		err = msgp.WrapError(err, "Single")
		return
	}
	// write "Array"
	err = en.Append(0xa5, 0x41, 0x72, 0x72, 0x61, 0x79)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Array)))
	if err != nil {
		err = msgp.WrapError(err, "Array")
		return
	}
	for za0001 := range z.Array {
		err = en.WriteString(string(z.Array[za0001]))
		if err != nil {
			err = msgp.WrapError(err, "Array", za0001)
			return
		}
	}
	// write "Map"
	err = en.Append(0xa3, 0x4d, 0x61, 0x70)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Map)))
	if err != nil {
		err = msgp.WrapError(err, "Map")
		return
	}
	for za0002, za0003 := range z.Map {
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Map")
			return
		}
		err = en.WriteString(string(za0003))
		if err != nil {
			err = msgp.WrapError(err, "Map", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *NumberJSONSampleReplace) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Single"
	o = append(o, 0x83, 0xa6, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65)
	o = msgp.AppendString(o, string(z.Single))
	// string "Array"
	o = append(o, 0xa5, 0x41, 0x72, 0x72, 0x61, 0x79)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Array)))
	for za0001 := range z.Array {
		o = msgp.AppendString(o, string(z.Array[za0001]))
	}
	// string "Map"
	o = append(o, 0xa3, 0x4d, 0x61, 0x70)
	o = msgp.AppendMapHeader(o, uint32(len(z.Map)))
	for za0002, za0003 := range z.Map {
		o = msgp.AppendString(o, za0002)
		o = msgp.AppendString(o, string(za0003))
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *NumberJSONSampleReplace) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Single":
			{
				var zb0002 string
				zb0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Single")
					return
				}
				z.Single = json.Number(zb0002)
			}
		case "Array":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Array")
				return
			}
			if cap(z.Array) >= int(zb0003) {
				z.Array = (z.Array)[:zb0003]
			} else {
				z.Array = make([]json.Number, zb0003)
			}
			for za0001 := range z.Array {
				{
					var zb0004 string
					zb0004, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Array", za0001)
						return
					}
					z.Array[za0001] = json.Number(zb0004)
				}
			}
		case "Map":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Map")
				return
			}
			if z.Map == nil {
				z.Map = make(map[string]json.Number, zb0005)
			} else if len(z.Map) > 0 {
				clear(z.Map)
			}
			for zb0005 > 0 {
				var za0003 json.Number
				zb0005--
				var za0002 string
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Map")
					return
				}
				{
					var zb0006 string
					zb0006, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Map", za0002)
						return
					}
					za0003 = json.Number(zb0006)
				}
				z.Map[za0002] = za0003
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NumberJSONSampleReplace) Msgsize() (s int) {
	s = 1 + 7 + msgp.StringPrefixSize + len(string(z.Single)) + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Array {
		s += msgp.StringPrefixSize + len(string(z.Array[za0001]))
	}
	s += 4 + msgp.MapHeaderSize
	if z.Map != nil {
		for za0002, za0003 := range z.Map {
			_ = za0003
			s += msgp.StringPrefixSize + len(za0002) + msgp.StringPrefixSize + len(string(za0003))
		}
	}
	return
}
